---
permalink: upgrade/linux-installing-rpm-or-deb-package-on-all-hosts.html 
sidebar: sidebar 
keywords: upgrade, linux, rpm, deb, 
summary: Linux 호스트에 구축된 StorageGRID 노드가 있는 경우 업그레이드를 시작하기 전에 각 호스트에 RPM 또는 DEB 패키지를 추가로 설치합니다. 
---
= Linux: 모든 호스트에 RPM 또는 DEB 패키지를 다운로드하고 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Linux 호스트에 구축된 StorageGRID 노드가 있는 경우 업그레이드를 시작하기 전에 각 호스트에 RPM 또는 DEB 패키지를 추가로 다운로드하여 설치하십시오.



== 업그레이드, Linux 및 핫픽스 파일을 다운로드합니다

그리드 관리자에서 StorageGRID 업그레이드를 수행할 때 업그레이드 아카이브와 필요한 핫픽스를 첫 번째 단계로 다운로드하라는 메시지가 표시됩니다. 그러나 Linux 호스트를 업그레이드하기 위해 파일을 다운로드해야 하는 경우 필요한 모든 파일을 미리 다운로드하여 시간을 절약할 수 있습니다.

.단계
. 로 이동합니다 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 다운로드: StorageGRID"^].
. 최신 릴리스를 다운로드하려면 버튼을 선택하거나 드롭다운 메뉴에서 다른 버전을 선택하고 * GO * 를 선택합니다.
+
StorageGRID 소프트웨어 버전의 형식은 11._x. y _ 입니다. StorageGRID 핫픽스의 형식은 11._x.x.x.z _ 입니다.

. NetApp 계정의 사용자 이름과 암호를 사용하여 로그인합니다.
. 주의/MustRead 알림이 나타나면 핫픽스 번호를 기록하고 확인란을 선택합니다.
. 최종 사용자 사용권 계약을 읽고 확인란을 선택한 다음 * 동의 및 계속 * 을 선택합니다.
+
선택한 버전의 다운로드 페이지가 나타납니다. 이 페이지에는 세 개의 열이 있습니다.

. 두 번째 열(* Upgrade StorageGRID*)에서 두 개의 파일을 다운로드합니다.
+
** 최신 릴리스에 대한 업그레이드 아카이브(이 파일은 * VMware, SG1000 또는 SG100 기본 관리 노드 * 라는 섹션에 있음) 이 파일은 업그레이드를 수행할 때까지 필요하지 않지만 지금 다운로드하면 시간이 절약됩니다.
** RPM 또는 DEB 아카이브 중 하나입니다 `.tgz` 또는 `.zip` 형식. 를 선택합니다 `.zip` 파일 - 서비스 랩톱에서 Windows를 실행 중인 경우
+
*** Red Hat Enterprise Linux+
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip` 를 누릅니다
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz`
*** Ubuntu 또는 Debian+
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip` 를 누릅니다
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz`




. 필요한 핫픽스로 인해 주의/MustRead 고지에 동의해야 하는 경우 핫픽스를 다운로드하십시오.
+
.. 로 돌아갑니다 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 다운로드: StorageGRID"^].
.. 드롭다운에서 핫픽스 번호를 선택합니다.
.. 주의 통지 및 EULA에 다시 동의합니다.
.. 핫픽스와 추가 정보를 다운로드하여 저장합니다.
+
업그레이드를 시작할 때 StorageGRID 업그레이드 페이지에 핫픽스 파일을 업로드하라는 메시지가 표시됩니다.







== 모든 Linux 호스트에 아카이브를 설치합니다

StorageGRID 소프트웨어를 업그레이드하기 전에 다음 단계를 수행하십시오.

.단계
. 설치 파일에서 RPM 또는 DEB 패키지를 추출합니다.
. 모든 Linux 호스트에 RPM 또는 DEB 패키지를 설치합니다.
+
설치 지침은 StorageGRID 호스트 서비스 설치 단계를 참조하십시오.

+
** link:../rhel/installing-storagegrid-webscale-host-service.html["Red Hat Enterprise Linux: StorageGRID 호스트 서비스를 설치합니다"]
** link:../ubuntu/installing-storagegrid-webscale-host-services.html["Ubuntu 또는 Debian: StorageGRID 호스트 서비스를 설치합니다"]


+
새 패키지는 추가 패키지로 설치됩니다. 기존 패키지를 제거하지 마십시오.


