---
permalink: swift/error-responses-to-swift-api-operations.html 
sidebar: sidebar 
keywords: swift api error responses 
summary: 가능한 오류 응답을 이해하면 작업 문제를 해결하는 데 도움이 됩니다. 
---
= Swift API 작업에 대한 오류 응답
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
가능한 오류 응답을 이해하면 작업 문제를 해결하는 데 도움이 됩니다.

작업 중에 오류가 발생하면 다음 HTTP 상태 코드가 반환될 수 있습니다.

|===
| SWIFT 오류 이름 | HTTP 상태입니다 


 a| 
AccountNameTooLong, ContainerNameTooLong, HeaderTooBig, InvalidContainerName, InvalidRequest, InvalidURI, MetadataNameTooLong, MetadataValueTooBig, MissingSecurityHeader, ObjectNameTooLong, TooManyContainers, TooManyMetadataItems, TotalMetadataTooLarge입니다
 a| 
400 잘못된 요청



 a| 
액세스가 거부되었습니다
 a| 
403 사용 금지



 a| 
ContainerNotEmpty , ContainerAlreadyExists
 a| 
409 충돌



 a| 
내부 오류입니다
 a| 
500 내부 서버 오류입니다



 a| 
InvalidRange 를 선택합니다
 a| 
416 요청된 범위가 충분하지 않습니다



 a| 
MethodNotAllowed 를 참조하십시오
 a| 
405 메서드를 사용할 수 없습니다



 a| 
MissingContentLength를 참조하십시오
 a| 
411 길이 필요



 a| 
지원되지 않습니다
 a| 
404를 찾을 수 없습니다



 a| 
구현되지 않았습니다
 a| 
501 구현되지 않음



 a| 
사전 조건에 실패했습니다
 a| 
412 전제 조건 실패



 a| 
리소스 NotFound 를 참조하십시오
 a| 
404를 찾을 수 없습니다



 a| 
권한이 없습니다
 a| 
401 승인되지 않음



 a| 
UnprocessableEntity입니다
 a| 
422 처리할 수 없는 엔터티

|===