---
permalink: swift/get-container-consistency-request.html 
sidebar: sidebar 
keywords: get container consistency request 
summary: 정합성 보장 값은 다양한 스토리지 노드 및 사이트에서 객체의 가용성과 정합성 간의 균형을 조정합니다. 컨테이너 정합성 보장 가져오기 요청을 사용하면 특정 컨테이너에 적용되는 일관성을 확인할 수 있습니다. 
---
= 컨테이너 일관성 요청 가져오기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
정합성 보장 값은 다양한 스토리지 노드 및 사이트에서 객체의 가용성과 정합성 간의 균형을 조정합니다. 컨테이너 정합성 보장 가져오기 요청을 사용하면 특정 컨테이너에 적용되는 일관성을 확인할 수 있습니다.



== 요청하십시오

[cols="2a,4a"]
|===
| HTTP 헤더를 요청합니다 | 설명 


| X-Auth - 토큰  a| 
요청에 사용할 계정의 Swift 인증 토큰을 지정합니다.



| X-NTAP-sg-정합성  a| 
요청 유형을 지정합니다. 여기서 는 `true` = 컨테이너 일관성 확보 및 `false` = 컨테이너를 가져옵니다.



| 호스트  a| 
요청이 전달되는 호스트 이름입니다.

|===


== 요청 예

[listing]
----
GET /v1/28544923908243208806/Swift container
X-Auth-Token: SGRD_3a877009a2d24cb1801587bfa9050f29
x-ntap-sg-consistency: true
Host: test.com
----


== 응답

[cols="2a,4a"]
|===
| 응답 HTTP 헤더 | 설명 


| 날짜  a| 
응답의 날짜 및 시간입니다.



| 연결  a| 
서버에 대한 연결이 열려 있는지 또는 닫혀 있는지 여부



| X-Trans-ID  a| 
요청에 대한 고유한 트랜잭션 식별자입니다.



| 콘텐츠 - 길이  a| 
응답 바디의 길이.



| X-NTAP-sg-정합성  a| 
컨테이너에 적용되는 정합성. 지원되는 값은 다음과 같습니다.

* ALL *: 모든 노드가 즉시 데이터를 수신하거나 요청이 실패합니다.

* 강력한 글로벌 *: 모든 사이트에서 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.

* 강력한 사이트 *: 사이트 내의 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.

*Read-after-new-write *: (기본값) 새 개체에 대해 읽기-쓰기 후 일관성을 제공하고 개체 업데이트에 대한 최종 일관성을 제공합니다. 고가용성 및 데이터 보호 보장 제공 대부분의 경우에 권장됩니다.

* 사용 가능 *: 새 객체 및 객체 업데이트 모두에 대한 최종 일관성을 제공합니다. S3 버킷의 경우 필요한 경우에만 사용하십시오(예: 거의 읽지 않는 로그 값이 포함된 버킷의 경우 또는 존재하지 않는 키의 헤드 또는 GET 작업의 경우). S3 FabricPool 버킷은 지원되지 않습니다.

|===


== 응답 예

[listing]
----
HTTP/1.1 204 No Content
Date: Sat, 29 Nov 2015 01:02:18 GMT
Connection: CLOSE
X-Trans-Id: 1936575373
Content-Length: 0
x-ntap-sg-consistency: strong-site
----