---
permalink: swift/storagegrid-swift-rest-api-operations.html 
sidebar: sidebar 
keywords: swift rest api operations 
summary: StorageGRID 시스템별 Swift REST API에 작업이 추가됩니다. 
---
= StorageGRID Swift REST API 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템별 Swift REST API에 작업이 추가됩니다.



== 컨테이너 일관성 요청 가져오기

link:../s3/consistency-controls.html["일관성 값"] 오브젝트의 가용성과 서로 다른 스토리지 노드 및 사이트에서 이러한 오브젝트의 일관성 간의 균형을 제공합니다. 컨테이너 정합성 보장 가져오기 요청을 사용하면 특정 컨테이너에 적용되는 일관성을 확인할 수 있습니다.



=== 요청하십시오

[cols="2a,4a"]
|===
| HTTP 헤더를 요청합니다 | 설명 


| X-Auth - 토큰  a| 
요청에 사용할 계정의 Swift 인증 토큰을 지정합니다.



| X-NTAP-sg-정합성  a| 
요청 유형을 지정합니다. 여기서 는 `true` = 컨테이너 일관성 확보 및 `false` = 컨테이너를 가져옵니다.



| 호스트  a| 
요청이 전달되는 호스트 이름입니다.

|===


=== 요청 예

[listing]
----
GET /v1/28544923908243208806/Swift container
X-Auth-Token: SGRD_3a877009a2d24cb1801587bfa9050f29
x-ntap-sg-consistency: true
Host: test.com
----


=== 응답

[cols="2a,4a"]
|===
| 응답 HTTP 헤더 | 설명 


| 날짜  a| 
응답의 날짜 및 시간입니다.



| 연결  a| 
서버에 대한 연결이 열려 있는지 또는 닫혀 있는지 여부



| X-Trans-ID  a| 
요청에 대한 고유한 트랜잭션 식별자입니다.



| 콘텐츠 - 길이  a| 
응답 바디의 길이.



| X-NTAP-sg-정합성  a| 
컨테이너에 적용되는 정합성. 지원되는 값은 다음과 같습니다.

* ALL *: 모든 노드가 즉시 데이터를 수신하거나 요청이 실패합니다.

* 강력한 글로벌 *: 모든 사이트에서 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.

* 강력한 사이트 *: 사이트 내의 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.

*Read-after-new-write *: (기본값) 새 개체에 대해 읽기-쓰기 후 일관성을 제공하고 개체 업데이트에 대한 최종 일관성을 제공합니다. 고가용성 및 데이터 보호 보장 제공 대부분의 경우에 권장됩니다.

* 사용 가능 *: 새 객체 및 객체 업데이트 모두에 대한 최종 일관성을 제공합니다. S3 버킷의 경우 필요한 경우에만 사용하십시오(예: 거의 읽지 않는 로그 값이 포함된 버킷의 경우 또는 존재하지 않는 키의 헤드 또는 GET 작업의 경우). S3 FabricPool 버킷은 지원되지 않습니다.

|===


=== 응답 예

[listing]
----
HTTP/1.1 204 No Content
Date: Sat, 29 Nov 2015 01:02:18 GMT
Connection: CLOSE
X-Trans-Id: 1936575373
Content-Length: 0
x-ntap-sg-consistency: strong-site
----


== 컨테이너 일관성 요청

Put container consistency request를 사용하면 컨테이너에서 수행되는 작업에 적용할 일관성을 지정할 수 있습니다. 기본적으로 새 컨테이너는 "Read-after-new-write" 정합성을 사용하여 생성됩니다.



=== 요청하십시오

[cols="2a,4a"]
|===
| HTTP 헤더를 요청합니다 | 설명 


| X-Auth - 토큰  a| 
요청에 사용할 계정의 Swift 인증 토큰입니다.



| X-NTAP-sg-정합성  a| 
컨테이너의 작업에 적용할 일관성입니다. 지원되는 값은 다음과 같습니다.

* ALL *: 모든 노드가 즉시 데이터를 수신하거나 요청이 실패합니다.

* 강력한 글로벌 *: 모든 사이트에서 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.

* 강력한 사이트 *: 사이트 내의 모든 클라이언트 요청에 대해 쓰기 후 읽기 일관성을 보장합니다.

*Read-after-new-write *: (기본값) 새 개체에 대해 읽기-쓰기 후 일관성을 제공하고 개체 업데이트에 대한 최종 일관성을 제공합니다. 고가용성 및 데이터 보호 보장 제공 대부분의 경우에 권장됩니다.

* 사용 가능 *: 새 객체 및 객체 업데이트 모두에 대한 최종 일관성을 제공합니다. S3 버킷의 경우 필요한 경우에만 사용하십시오(예: 거의 읽지 않는 로그 값이 포함된 버킷의 경우 또는 존재하지 않는 키의 헤드 또는 GET 작업의 경우). S3 FabricPool 버킷은 지원되지 않습니다.



 a| 
`Host`
 a| 
요청이 전달되는 호스트 이름입니다.

|===


=== 일관성과 ILM 규칙이 데이터 보호에 영향을 미치는 방식

둘 다 선택할 수 있습니다 link:../s3/consistency-controls.html["정합성 보장 값"] ILM 규칙은 개체의 보호 방법에 영향을 줍니다. 이러한 설정은 상호 작용할 수 있습니다.

예를 들어, 오브젝트가 저장될 때 사용되는 일관성은 오브젝트 메타데이터의 초기 배치에 영향을 주고 에는 영향을 미칩니다 link:../ilm/what-ilm-rule-is.html#ilm-rule-ingest-behavior["수집 동작"] ILM 규칙에 대해 선택된 은 오브젝트 복사본의 초기 배치에 영향을 줍니다. StorageGRID에서는 클라이언트 요청을 이행하기 위해 오브젝트의 메타데이터와 해당 데이터에 모두 액세스해야 하므로 일관성 및 수집 동작에 대해 일치하는 보호 수준을 선택하면 초기 데이터 보호 수준을 높이고 시스템 응답을 보다 예측 가능하게 할 수 있습니다.



=== 일관성과 ILM 규칙이 상호 작용하는 방법의 예

다음과 같은 ILM 규칙과 다음과 같은 일관성이 있는 2개 사이트 그리드가 있다고 가정합니다.

* * ILM 규칙 *: 로컬 사이트와 원격 사이트에 각각 하나씩, 두 개의 오브젝트 복사본을 만듭니다. Strict 수집 동작이 선택됩니다.
* **: "Strong-global"(개체 메타데이터가 모든 사이트에 즉시 배포됩니다.)


클라이언트가 오브젝트를 그리드에 저장할 때 StorageGRID는 오브젝트 복사본을 둘 다 만들고 메타데이터를 두 사이트에 분산한 다음 클라이언트에 성공을 반환합니다.

수집 성공 메시지가 표시된 시점에 객체가 손실로부터 완벽하게 보호됩니다. 예를 들어, 수집 직후 로컬 사이트가 손실되면 오브젝트 데이터와 오브젝트 메타데이터의 복사본이 원격 사이트에 계속 존재합니다. 개체를 완전히 검색할 수 있습니다.

대신 동일한 ILM 규칙과 "강력한 사이트" 일관성을 사용한 경우 객체 데이터가 원격 사이트에 복제된 후 객체 메타데이터가 이 사이트에 배포되기 전에 클라이언트에서 성공 메시지를 받을 수 있습니다. 이 경우 오브젝트 메타데이터의 보호 수준이 오브젝트 데이터의 보호 수준과 일치하지 않습니다. 수집 후 곧바로 로컬 사이트가 손실되면 오브젝트 메타데이터가 손실됩니다. 개체를 검색할 수 없습니다.

일관성과 ILM 규칙 간의 상호 관계는 복잡할 수 있습니다. 도움이 필요한 경우 NetApp에 문의하십시오.



=== 요청 예

[listing]
----
PUT /v1/28544923908243208806/_Swift container_
X-Auth-Token: SGRD_3a877009a2d24cb1801587bfa9050f29
x-ntap-sg-consistency: strong-site
Host: test.com
----


=== 응답

[cols="1a,2a"]
|===
| 응답 HTTP 헤더 | 설명 


 a| 
`Date`
 a| 
응답의 날짜 및 시간입니다.



 a| 
`Connection`
 a| 
서버에 대한 연결이 열려 있는지 또는 닫혀 있는지 여부



 a| 
`X-Trans-Id`
 a| 
요청에 대한 고유한 트랜잭션 식별자입니다.



 a| 
`Content-Length`
 a| 
응답 바디의 길이.

|===


=== 응답 예

[listing]
----
HTTP/1.1 204 No Content
Date: Sat, 29 Nov 2015 01:02:18 GMT
Connection: CLOSE
X-Trans-Id: 1936575373
Content-Length: 0
----