---
permalink: tenant/configuration-xml-for-search-configuration.html 
sidebar: sidebar 
keywords: search integration, configuration xml, metadata notification, container tag, urn 
summary: 검색 통합 서비스는 <MetadataNotificationConfiguration\> 및 </MetadataNotificationConfiguration\> 태그에 포함된 규칙 집합을 사용하여 구성됩니다. 각 규칙은 규칙이 적용되는 개체와 StorageGRID가 해당 개체의 메타데이터를 보내야 하는 대상을 지정합니다. 
---
= 검색 통합을 위한 구성 XML
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
검색 통합 서비스는 에 포함된 규칙 집합을 사용하여 구성됩니다 `<MetadataNotificationConfiguration>` 및 `</MetadataNotificationConfiguration>` 태그. 각 규칙은 규칙이 적용되는 오브젝트와 StorageGRID가 해당 오브젝트의 메타데이터를 보내야 하는 대상을 지정합니다.

개체 이름의 접두어를 기준으로 개체를 필터링할 수 있습니다. 예를 들어, 접두사가 있는 개체에 대한 메타데이터를 보낼 수 있습니다 `images` 대상이 하나인 경우 및 접두사가 있는 개체의 메타데이터입니다 `videos` 다른 사람에게. 중복되는 접두사가 있는 구성은 유효하지 않으며 제출될 때 거부됩니다. 예를 들어, 접두사가 있는 개체에 대해 하나의 규칙을 포함하는 구성입니다 `test` 접두사가 있는 개체에 대한 두 번째 규칙입니다 `test2` 허용되지 않습니다.

검색 통합 서비스를 위해 생성된 StorageGRID 엔드포인트의 URN을 사용하여 대상을 지정해야 합니다. 이러한 엔드포인트는 Elasticsearch 클러스터에 정의된 인덱스 및 유형을 나타냅니다.

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>rule-status</Status>
        <Prefix>key-prefix</Prefix>
        <Destination>
           <Urn>arn:aws:es:region:account-ID:domain/mydomain/myindex/mytype</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Rule-2</ID>
         ...
    </Rule>
     ...
</MetadataNotificationConfiguration>
----
이 표에서는 메타데이터 알림 구성 XML의 요소에 대해 설명합니다.

[cols="2a,3a,1a"]
|===
| 이름 | 설명 | 필수 요소입니다 


 a| 
MetadataNotificationConfiguration을 참조하십시오
 a| 
메타데이터 알림의 개체 및 대상을 지정하는 데 사용되는 규칙의 컨테이너 태그입니다.

하나 이상의 규칙 요소가 포함되어 있습니다.
 a| 
예



 a| 
규칙
 a| 
메타데이터를 지정된 인덱스에 추가해야 하는 개체를 식별하는 규칙의 컨테이너 태그입니다.

접두사가 겹치는 규칙은 거부됩니다.

MetadataNotificationConfiguration 요소에 포함되어 있습니다.
 a| 
예



 a| 
ID입니다
 a| 
규칙의 고유 식별자입니다.

Rule 요소에 포함되어 있습니다.
 a| 
아니요



 a| 
상태
 a| 
상태는 '활성화' 또는 '비활성화'가 될 수 있습니다. 비활성화된 규칙에 대해 어떠한 작업도 수행되지 않습니다.

Rule 요소에 포함되어 있습니다.
 a| 
예



 a| 
접두어
 a| 
접두사와 일치하는 개체는 규칙의 영향을 받으며 해당 메타데이터는 지정된 대상으로 전송됩니다.

모든 오브젝트를 일치시키려면 빈 접두사를 지정합니다.

Rule 요소에 포함되어 있습니다.
 a| 
예



 a| 
목적지
 a| 
규칙의 대상에 대한 컨테이너 태그입니다.

Rule 요소에 포함되어 있습니다.
 a| 
예



 a| 
urn
 a| 
객체 메타데이터가 전송되는 대상의 urn입니다. 다음 속성을 가진 StorageGRID 끝점의 URN이어야 합니다.

* `es` 세 번째 요소여야 합니다.
* URN은 메타데이터가 저장된 인덱스 및 형식으로 양식에 끝나야 합니다 `domain-name/myindex/mytype`.


엔드포인트는 테넌트 관리자 또는 테넌트 관리 API를 사용하여 구성됩니다. 다음과 같은 형식을 취합니다.

* `arn:aws:es:region:account-ID:domain/mydomain/myindex/mytype`
* `urn:mysite:es:::mydomain/myindex/mytype`


구성 XML을 제출하기 전에 끝점을 구성해야 합니다. 그렇지 않으면 404 오류로 인해 구성이 실패합니다.

urn은 Destination 요소에 포함됩니다.
 a| 
예

|===
샘플 메타데이터 알림 구성 XML을 사용하여 고유한 XML을 구성하는 방법을 배웁니다.



== 모든 개체에 적용되는 메타데이터 알림 구성입니다

이 예제에서 모든 오브젝트의 오브젝트 메타데이터는 동일한 대상으로 전송됩니다.

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>Enabled</Status>
        <Prefix></Prefix>
        <Destination>
           <Urn>urn:myes:es:::sgws-notifications/test1/all</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----


== 두 가지 규칙을 사용하여 메타데이터 알림 구성

이 예제에서는 접두사와 일치하는 개체의 개체 메타데이터를 보여 줍니다 `/images` 은(는) 한 대상으로 전송되지만 접두사와 일치하는 오브젝트의 오브젝트 메타데이터는 전송됩니다 `/videos` 두 번째 대상으로 전송됩니다.

[listing]
----

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Images-rule</ID>
        <Status>Enabled</Status>
        <Prefix>/images</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-east-1:3333333:domain/es-domain/graphics/imagetype</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Videos-rule</ID>
        <Status>Enabled</Status>
        <Prefix>/videos</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-west-1:22222222:domain/es-domain/graphics/videotype</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
.관련 정보
link:../s3/index.html["S3 REST API 사용"]

link:object-metadata-included-in-metadata-notifications.html["메타데이터 알림에 포함된 개체 메타데이터입니다"]

link:json-generated-by-search-integration-service.html["JSON이 검색 통합 서비스에 의해 생성되었습니다"]

link:configuring-search-integration-service.html["검색 통합 서비스를 구성합니다"]
