---
permalink: tenant/considerations-for-platform-services.html 
sidebar: sidebar 
keywords: considerations for using platform services 
summary: 플랫폼 서비스를 구현하기 전에 이러한 서비스를 사용하기 위한 권장 사항 및 고려 사항을 검토하십시오. 
---
= 플랫폼 서비스에 대한 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
플랫폼 서비스를 구현하기 전에 이러한 서비스를 사용하기 위한 권장 사항 및 고려 사항을 검토하십시오.

S3에 대한 자세한 내용은 을 참조하십시오 link:../s3/index.html["S3 REST API 사용"].



== 플랫폼 서비스 사용에 대한 고려 사항

[cols="1a,3a"]
|===
| 고려 사항 | 세부 정보 


 a| 
대상 엔드포인트 모니터링
 a| 
각 대상 끝점의 가용성을 모니터링해야 합니다. 대상 끝점에 대한 연결이 오랜 시간 동안 손실되고 요청의 백로그가 많은 경우 StorageGRID에 대한 추가 클라이언트 요청(예: PUT 요청)이 실패합니다. 엔드포인트에 연결할 수 있게 되면 실패한 요청을 다시 시도해야 합니다.



 a| 
대상 끝점 임계치 조절
 a| 
요청이 전송되는 속도가 대상 엔드포인트에서 요청을 수신할 수 있는 속도를 초과하는 경우 StorageGRID 소프트웨어는 버킷에 대한 수신 S3 요청을 스로틀할 수 있습니다. 임계치 조절은 대상 끝점으로 보내려고 기다리는 요청의 백로그가 있는 경우에만 발생합니다.

단, 들어오는 S3 요청의 실행 시간이 더 오래 걸린다는 점을 알 수 있습니다. 속도가 현저히 느린 성능을 감지하기 시작하는 경우 수집 속도를 줄이거나 용량이 더 큰 엔드포인트를 사용해야 합니다. 요청 백로그가 계속 증가하는 경우 PUT 요청과 같은 클라이언트 S3 작업이 결국 실패합니다.

CloudMirror 요청은 일반적으로 검색 통합 또는 이벤트 알림 요청보다 더 많은 데이터 전송을 포함하므로 대상 엔드포인트의 성능에 영향을 받을 가능성이 더 높습니다.



 a| 
주문 보증
 a| 
StorageGRID은 사이트 내의 개체에 대한 작업을 주문할 수 있도록 보장합니다. 객체에 대한 모든 작업이 동일한 사이트 내에 있는 한 최종 객체 상태(복제의 경우)는 항상 StorageGRID의 상태와 동일합니다.

StorageGRID는 StorageGRID 사이트 전체에서 작업이 수행되는 경우 요청을 주문하기 위해 최선의 노력을 다하고 있습니다. 예를 들어 처음에 사이트 A에 오브젝트를 작성한 다음 나중에 사이트 B에서 동일한 오브젝트를 덮어쓰는 경우 CloudMirror에서 대상 버킷에 복제한 최종 오브젝트는 새로운 오브젝트일 수 없습니다.



 a| 
ILM 기반 오브젝트 삭제
 a| 
AWS CRR 및 Amazon Simple Notification Service의 삭제 동작과 일치시키기 위해 StorageGRID ILM 규칙으로 인해 소스 버킷의 오브젝트가 삭제될 때 CloudMirror 및 이벤트 알림 요청이 전송되지 않습니다. 예를 들어 ILM 규칙이 14일 후에 개체를 삭제하는 경우 CloudMirror 또는 이벤트 알림 요청이 전송되지 않습니다.

반면, 검색 통합 요청은 ILM로 인해 객체가 삭제될 때 전송됩니다.



 a| 
Kafka 엔드포인트 사용
 a| 
Kafka 엔드포인트의 경우 상호 TLS는 지원되지 않습니다. 그 결과 `ssl.client.auth` 를 로 설정합니다 `required` Kafka 브로커 구성에서 Kafka 엔드포인트 구성 문제를 유발할 수 있습니다.

Kafka 엔드포인트 인증은 다음과 같은 인증 유형을 사용합니다. 이러한 유형은 Amazon SNS와 같은 다른 엔드포인트의 인증에 사용되는 유형과는 다르며 사용자 이름 및 암호 자격 증명이 필요합니다.

* SASL/일반
* SASL/SCRAM-SHA-256
* SASL/SCRAM-SHA-512


* 참고: * 구성된 스토리지 프록시 설정은 Kafka 플랫폼 서비스 엔드포인트에 적용되지 않습니다.

|===


== CloudMirror 복제 서비스 사용에 대한 고려 사항

[cols="1a,3a"]
|===
| 고려 사항 | 세부 정보 


 a| 
복제 상태입니다
 a| 
StorageGRID는 을 지원하지 않습니다 `x-amz-replication-status` 머리글.



 a| 
개체 크기
 a| 
CloudMirror 복제 서비스를 통해 대상 버킷에 복제할 수 있는 개체의 최대 크기는 5TiB이며, 이는 maximum_supported_object 크기와 같습니다.

* 참고 *: 단일 PutObject 작업의 maximum_recommended_size는 5GiB(5,368,709,120바이트)입니다. 5GiB보다 큰 객체가 있는 경우 대신 멀티파트 업로드를 사용합니다.



 a| 
버킷 버전 관리 및 버전 ID
 a| 
StorageGRID의 소스 S3 버킷에서 버전 관리가 활성화된 경우 대상 버킷의 버전 관리도 활성화해야 합니다.

버전 관리를 사용할 때는 S3 프로토콜의 제한으로 인해 대상 버킷에서 오브젝트 버전 순서가 CloudMirror 서비스에 의해 보장되지 않는 것이 가장 좋습니다.

* 참고 *: StorageGRID의 소스 버킷에 대한 버전 ID는 대상 버킷의 버전 ID와 관련이 없습니다.



 a| 
개체 버전에 태그 달기
 a| 
CloudMirror 서비스는 S3 프로토콜의 제한으로 인해 버전 ID를 제공하는 PutObjectTagging 또는 DeleteObjectTagging 요청을 복제하지 않습니다. 소스 및 대상의 버전 ID는 관련이 없으므로 특정 버전 ID에 대한 태그 업데이트를 복제할 수 없습니다.

반면, CloudMirror 서비스는 버전 ID를 지정하지 않는 PutObjectTagging 요청이나 DeleteObjectTagging 요청을 복제합니다. 이러한 요청은 최신 키의 태그(또는 버킷의 버전이 지정된 경우 최신 버전)를 업데이트합니다. 태그가 있는 일반 베스트(업데이트 태그 지정 안 함)도 복제됩니다.



 a| 
멀티파트 업로드 및 `ETag` 값
 a| 
여러 부분 업로드를 사용하여 업로드한 개체를 미러링할 때 CloudMirror 서비스는 해당 파트를 보존하지 않습니다. 그 결과, 가 표시됩니다 `ETag` 대칭 복사된 개체의 값은 과 다릅니다 `ETag` 원래 오브젝트의 값입니다.



 a| 
SSE-C로 암호화된 오브젝트(고객이 제공한 키를 사용한 서버측 암호화)
 a| 
CloudMirror 서비스는 SSE-C로 암호화된 객체를 지원하지 않습니다 CloudMirror 복제를 위해 소스 버킷으로 객체를 수집하려고 하고 요청에 SSE-C 요청 헤더가 포함된 경우 작업이 실패합니다.



 a| 
S3 오브젝트 잠금이 활성화된 버킷
 a| 
CloudMirror 복제용 대상 S3 버킷에 S3 오브젝트 잠금이 설정되어 있는 경우 버킷 복제(PutBucketReplication) 구성 시도가 실패하고 AccessDenied 오류가 발생합니다.

|===