---
permalink: vmware/automating-grid-node-deployment-in-vmware-vsphere.html 
sidebar: sidebar 
keywords: how to automate installation 
summary: VMware vSphere를 사용하여 그리드 노드 구축을 자동화할 수 있습니다. StorageGRID의 구성을 자동화할 수도 있습니다. 
---
= 설치 자동화(VMware)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere를 사용하여 그리드 노드 구축을 자동화할 수 있습니다. StorageGRID의 구성을 자동화할 수도 있습니다.



== 그리드 노드 구축을 자동화합니다

VMware vSphere를 사용하여 그리드 노드의 구축을 자동화합니다.

.시작하기 전에
* Bash 3.2 이상이 설치된 Linux/Unix 시스템에 액세스할 수 있습니다.
* VMware OVF Tool 4.1이 설치되고 올바르게 구성되었습니다.
* OVF 툴을 사용하여 VMware vSphere에 액세스하는 데 필요한 사용자 이름과 암호를 알고 있습니다.
* StorageGRID 가상 머신을 구축할 vSphere의 위치에 대한 VI(가상 인프라) URL을 알고 있습니다. 이 URL은 일반적으로 vApp 또는 리소스 풀이 됩니다. 예를 들면 다음과 같습니다. `vi://vcenter.example.com/vi/sgws`
+

NOTE: VMware를 사용할 수 있습니다 `ovftool` 유틸리티를 사용하여 이 값을 확인합니다( 참조) `ovftool` 문서 참조).

+

NOTE: vApp에 구축할 경우 가상 머신이 처음 시작될 때 자동으로 시작되지 않으며 수동으로 전원을 설정해야 합니다.

* 구성 파일에 필요한 모든 정보를 수집했습니다. 을 참조하십시오 link:collecting-information-about-your-deployment-environment.html["배포 환경에 대한 정보를 수집합니다"] 를 참조하십시오.
* StorageGRID용 VMware 설치 아카이브에서 다음 파일에 액세스할 수 있습니다.


[cols="1a,1a"]
|===
| 파일 이름 | 설명 


| NetApp-SG-version-SHA.vmdk입니다  a| 
그리드 노드 가상 머신을 생성하기 위한 템플릿으로 사용되는 가상 머신 디스크 파일입니다.

* 참고: * 이 파일은 와 동일한 폴더에 있어야 합니다 `.ovf` 및 `.mf` 파일.



| vsphere-primary-admin.ovf 를 참조하십시오

vsphere-primary-admin.mf  a| 
Open Virtualization Format 템플릿 파일입니다 (`.ovf`) 및 매니페스트 파일 (`.mf`)를 참조하십시오.



| vsphere-non-primary-admin.ovf 를 참조하십시오

vsphere-non-primary-admin.mf  a| 
템플릿 파일입니다 (`.ovf`) 및 매니페스트 파일 (`.mf`)를 참조하십시오.



| vSphere - archive.ovf

vSphere - archive.mf  a| 
템플릿 파일입니다 (`.ovf`) 및 매니페스트 파일 (`.mf`)를 참조하십시오.



| vsphere - gateway.ovf

vsphere - gateway.mf  a| 
템플릿 파일입니다 (`.ovf`) 및 매니페스트 파일 (`.mf`)를 참조하십시오.



| vSphere - storage.ovf

vsphere-storage.mf  a| 
템플릿 파일입니다 (`.ovf`) 및 매니페스트 파일 (`.mf`)를 참조하십시오.



| deploy-vsphere-ovftool.sh  a| 
가상 그리드 노드의 배포를 자동화하는 데 사용되는 Bash 쉘 스크립트입니다.



| deploy-vsphere-ovftool-sample.ini  a| 
와 함께 사용할 예제 구성 파일입니다 `deploy-vsphere-ovftool.sh` 스크립트.

|===


=== 배포를 위한 구성 파일을 정의합니다

에서 사용하는 구성 파일에 StorageGRID용 가상 그리드 노드를 구축하는 데 필요한 정보를 지정합니다 `deploy-vsphere-ovftool.sh` Bash 스크립트. 예제 구성 파일을 수정하여 처음부터 새로 만들 필요가 없도록 할 수 있습니다.

.단계
. 예제 구성 파일의 복사본을 만듭니다 (`deploy-vsphere-ovftool.sample.ini`)를 클릭합니다. 새 파일을 다른 이름으로 저장합니다 `deploy-vsphere-ovftool.ini` 와 동일한 디렉토리에 있습니다 `deploy-vsphere-ovftool.sh`.
. 개방형 `deploy-vsphere-ovftool.ini`.
. VMware 가상 그리드 노드를 구축하는 데 필요한 모든 정보를 입력합니다.
+
을 참조하십시오 <<configuration-file-settings,구성 파일 설정>> 를 참조하십시오.

. 필요한 모든 정보를 입력하고 확인했으면 파일을 저장하고 닫습니다.




=== 구성 파일 설정

를 클릭합니다 `deploy-vsphere-ovftool.ini` 구성 파일에는 가상 그리드 노드를 구축하는 데 필요한 설정이 포함되어 있습니다.

구성 파일은 먼저 글로벌 매개 변수를 나열한 다음 노드 이름으로 정의된 섹션에 노드별 매개 변수를 나열합니다. 파일이 사용되는 경우:

* _Global parameters_는 모든 그리드 노드에 적용됩니다.
* _노드별 parameters_override 전역 매개 변수입니다.




==== 전역 매개 변수

전역 매개 변수는 개별 섹션의 설정에 의해 재정의되지 않는 한 모든 그리드 노드에 적용됩니다. 전역 매개 변수 섹션에서 여러 노드에 적용되는 매개 변수를 배치한 다음 필요에 따라 개별 노드의 섹션에서 이러한 설정을 재정의합니다.

* * OVFTOOL_Arguments *: OVFTOOL_Arguments을 전역 설정으로 지정하거나 특정 노드에 인수를 개별적으로 적용할 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing, subs="specialcharacters,quotes"]
----
OVFTOOL_ARGUMENTS = --powerOn --noSSLVerify --diskMode=eagerZeroedThick --datastore='_datastore_name_'
----
+
를 사용할 수 있습니다 `--powerOffTarget` 및 `--overwrite` 기존 가상 시스템을 종료하고 교체하는 옵션.

+

CAUTION: 노드를 서로 다른 데이터 저장소에 배포하고 전역이 아닌 각 노드에 대해 OVFTOOL_MOUMENT를 지정해야 합니다.

* * 소스 *: StorageGRID 가상 머신 템플릿의 경로입니다 (`.vmdk`) 파일 및 `.ovf` 및 `.mf` 개별 그리드 노드에 대한 파일. 이 기본값은 현재 디렉터리입니다.
+
[listing, subs="specialcharacters,quotes"]
----
SOURCE = /downloads/StorageGRID-Webscale-_version_/vsphere
----
* * 타겟 *: StorageGRID를 구축할 위치의 VMware vSphere 가상 인프라(vi) URL입니다. 예를 들면 다음과 같습니다.
+
[listing]
----
TARGET = vi://vcenter.example.com/vm/sgws
----
* * GRID_NETWORK_CONFIG *: 고정 또는 DHCP 중 IP 주소를 획득하는 데 사용되는 방법입니다. 기본값은 정적입니다. 모든 노드 또는 대부분의 노드가 동일한 방법으로 IP 주소를 획득하는 경우 여기에서 해당 방법을 지정할 수 있습니다. 그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 전역 설정을 재정의할 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
GRID_NETWORK_CONFIG = DHCP
----
* * GRID_NETWORK_TARGET *: 그리드 네트워크에 사용할 기존 VMware 네트워크의 이름입니다. 모든 노드 또는 대부분의 노드가 동일한 네트워크 이름을 사용하는 경우 여기에서 지정할 수 있습니다. 그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 전역 설정을 재정의할 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
GRID_NETWORK_TARGET = SG-Admin-Network
----
* grid_network_mask *: 그리드 네트워크의 네트워크 마스크. 모든 노드 또는 대부분의 노드가 동일한 네트워크 마스크를 사용하는 경우 여기에서 지정할 수 있습니다. 그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 전역 설정을 재정의할 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
GRID_NETWORK_MASK = 255.255.255.0
----
* grid_network_gateway *: 그리드 네트워크의 네트워크 게이트웨이. 모든 노드 또는 대부분의 노드가 동일한 네트워크 게이트웨이를 사용하는 경우 여기에서 지정할 수 있습니다. 그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 전역 설정을 재정의할 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
GRID_NETWORK_GATEWAY = 10.1.0.1
----
* *GRID_NETWORK_MTU *: 선택 사항. Grid Network의 MTU(Maximum Transmission Unit)입니다. 지정된 경우 값은 1280에서 9216 사이여야 합니다. 예를 들면 다음과 같습니다.
+
[listing]
----
GRID_NETWORK_MTU = 8192
----
+
이 인수를 생략하면 1400이 사용됩니다.

+
점보 프레임을 사용하려면 MTU를 9000과 같은 점보 프레임에 적합한 값으로 설정합니다. 그렇지 않으면 기본값을 유지합니다.

+

NOTE: 네트워크의 MTU 값은 노드가 연결된 스위치 포트에 구성된 값과 일치해야 합니다. 그렇지 않으면 네트워크 성능 문제 또는 패킷 손실이 발생할 수 있습니다.

+

NOTE: 최상의 네트워크 성능을 얻으려면 모든 노드를 그리드 네트워크 인터페이스에서 유사한 MTU 값으로 구성해야 합니다. 개별 노드의 그리드 네트워크에 대한 MTU 설정에 상당한 차이가 있을 경우 * Grid Network MTU mismatch * 경고가 트리거됩니다. MTU 값은 모든 네트워크 유형에 대해 같을 필요는 없습니다.

* * admin_network_Config *: IP 주소를 획득하는 데 사용되는 방법으로, 비활성화, 정적 또는 DHCP입니다. 기본값은 사용 안 함으로 설정되어 있습니다. 모든 노드 또는 대부분의 노드가 동일한 방법으로 IP 주소를 획득하는 경우 여기에서 해당 방법을 지정할 수 있습니다. 그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 전역 설정을 재정의할 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
ADMIN_NETWORK_CONFIG = STATIC
----
* * admin_network_target *: 관리 네트워크에 사용할 기존 VMware 네트워크의 이름입니다. 이 설정은 관리 네트워크를 사용하지 않는 한 필요합니다. 모든 노드 또는 대부분의 노드가 동일한 네트워크 이름을 사용하는 경우 여기에서 지정할 수 있습니다. 그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 전역 설정을 재정의할 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
ADMIN_NETWORK_TARGET = SG-Admin-Network
----
* * admin_network_mask *: 관리 네트워크의 네트워크 마스크입니다. 이 설정은 고정 IP 주소 지정을 사용하는 경우에 필요합니다. 모든 노드 또는 대부분의 노드가 동일한 네트워크 마스크를 사용하는 경우 여기에서 지정할 수 있습니다. 그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 전역 설정을 재정의할 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
ADMIN_NETWORK_MASK = 255.255.255.0
----
* * admin_network_gateway *: 관리 네트워크의 네트워크 게이트웨이입니다. 이 설정은 정적 IP 주소 지정을 사용하고 admin_network_ESL 설정에서 외부 서브넷을 지정하는 경우에 필요합니다. (즉, admin_network_ESL이 비어 있으면 필요하지 않습니다.) 모든 노드 또는 대부분의 노드가 동일한 네트워크 게이트웨이를 사용하는 경우 여기에서 지정할 수 있습니다. 그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 전역 설정을 재정의할 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
ADMIN_NETWORK_GATEWAY = 10.3.0.1
----
* * admin_network_ESL *: 쉼표로 구분된 CIDR 라우트 대상 목록으로 지정된 관리 네트워크의 외부 서브넷 목록(라우트). 모든 노드 또는 대부분의 노드가 동일한 외부 서브넷 목록을 사용하는 경우 여기에서 지정할 수 있습니다. 그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 전역 설정을 재정의할 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
ADMIN_NETWORK_ESL = 172.16.0.0/21,172.17.0.0/21
----
* * admin_network_mtu *: 선택 사항. 관리자 네트워크의 MTU(Maximum Transmission Unit) admin_network_Config=DHCP인지 지정하지 마십시오. 지정된 경우 값은 1280에서 9216 사이여야 합니다. 이 인수를 생략하면 1400이 사용됩니다. 점보 프레임을 사용하려면 MTU를 9000과 같은 점보 프레임에 적합한 값으로 설정합니다. 그렇지 않으면 기본값을 유지합니다. 모든 노드 또는 대부분의 노드가 Admin Network에 대해 동일한 MTU를 사용하는 경우 여기에서 지정할 수 있습니다. 그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 전역 설정을 재정의할 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
ADMIN_NETWORK_MTU = 8192
----
* * CLIENT_NETWORK_CONFIG *: IP 주소를 획득하는 데 사용되는 방법으로, 비활성화, 정적 또는 DHCP입니다. 기본값은 사용 안 함으로 설정되어 있습니다. 모든 노드 또는 대부분의 노드가 동일한 방법으로 IP 주소를 획득하는 경우 여기에서 해당 방법을 지정할 수 있습니다. 그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 전역 설정을 재정의할 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
CLIENT_NETWORK_CONFIG = STATIC
----
* * client_network_target *: 클라이언트 네트워크에 사용할 기존 VMware 네트워크의 이름입니다. 이 설정은 클라이언트 네트워크를 사용하지 않는 경우에만 필요합니다. 모든 노드 또는 대부분의 노드가 동일한 네트워크 이름을 사용하는 경우 여기에서 지정할 수 있습니다. 그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 전역 설정을 재정의할 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
CLIENT_NETWORK_TARGET = SG-Client-Network
----
* * client_network_mask *: 클라이언트 네트워크의 네트워크 마스크입니다. 이 설정은 고정 IP 주소 지정을 사용하는 경우에 필요합니다. 모든 노드 또는 대부분의 노드가 동일한 네트워크 마스크를 사용하는 경우 여기에서 지정할 수 있습니다. 그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 전역 설정을 재정의할 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
CLIENT_NETWORK_MASK = 255.255.255.0
----
* * client_network_gateway *: 클라이언트 네트워크의 네트워크 게이트웨이입니다. 이 설정은 고정 IP 주소 지정을 사용하는 경우에 필요합니다. 모든 노드 또는 대부분의 노드가 동일한 네트워크 게이트웨이를 사용하는 경우 여기에서 지정할 수 있습니다. 그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 전역 설정을 재정의할 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
CLIENT_NETWORK_GATEWAY = 10.4.0.1
----
* * client_network_mtu *: 선택 사항. 클라이언트 네트워크의 MTU(Maximum Transmission Unit) client_network_Config = DHCP인지 지정하지 마십시오. 지정된 경우 값은 1280에서 9216 사이여야 합니다. 이 인수를 생략하면 1400이 사용됩니다. 점보 프레임을 사용하려면 MTU를 9000과 같은 점보 프레임에 적합한 값으로 설정합니다. 그렇지 않으면 기본값을 유지합니다. 모든 노드 또는 대부분의 노드가 클라이언트 네트워크에 동일한 MTU를 사용하는 경우 여기에서 지정할 수 있습니다. 그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 전역 설정을 재정의할 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
CLIENT_NETWORK_MTU = 8192
----
* * port_remap *: 내부 그리드 노드 통신 또는 외부 통신을 위해 노드에서 사용하는 포트를 다시 매핑합니다. 엔터프라이즈 네트워킹 정책이 StorageGRID에서 사용하는 하나 이상의 포트를 제한하는 경우 포트를 다시 매핑해야 합니다. StorageGRID에서 사용하는 포트 목록은 의 내부 그리드 노드 통신 및 외부 통신 을 참조하십시오 link:../network/index.html["네트워킹 지침"].
+

NOTE: 로드 밸런서 엔드포인트를 구성하는 데 사용할 포트를 다시 매핑하지 마십시오.

+

NOTE: port_remap 만 설정된 경우 지정하는 매핑이 인바운드 및 아웃바운드 통신 모두에 사용됩니다. port_remap_inbound 도 지정된 경우 port_remap 은 아웃바운드 통신에만 적용됩니다.

+
사용되는 형식은 다음과 같습니다. `_network type/protocol/default port used by grid node/new port_`네트워크 유형이 grid, admin 또는 client이고 프로토콜은 TCP 또는 UDP입니다.

+
예를 들면 다음과 같습니다.

+
[listing]
----
PORT_REMAP = client/tcp/18082/443
----
+
단독으로 사용하는 경우 이 예제 설정은 그리드 노드에 대한 인바운드 및 아웃바운드 통신을 포트 18082에서 포트 443으로 대칭적으로 매핑합니다. port_remap_inbound 와 함께 사용할 경우 이 예제 설정은 포트 18082에서 포트 443으로 아웃바운드 통신을 매핑합니다.

* * port_remap_inbound *: 지정된 포트에 대한 인바운드 통신을 다시 매핑합니다. port_remap_inbound 를 지정하지만 port_remap 의 값을 지정하지 않으면 포트의 아웃바운드 통신이 변경되지 않습니다.
+

NOTE: 로드 밸런서 엔드포인트를 구성하는 데 사용할 포트를 다시 매핑하지 마십시오.

+
사용되는 형식은 다음과 같습니다. `_network type_/_protocol/_default port used by grid node_/_new port_`네트워크 유형이 grid, admin 또는 client이고 프로토콜은 TCP 또는 UDP입니다.

+
예를 들면 다음과 같습니다.

+
[listing]
----
PORT_REMAP_INBOUND = client/tcp/443/18082
----
+
이 예에서는 포트 443으로 전송된 트래픽을 내부 방화벽을 통과하여 그리드 노드가 S3 요청을 수신하는 포트 18082로 전달합니다.

* *Temporary_password_type*: 노드가 그리드에 합류하기 전에 VM 콘솔에 액세스하거나 SSH를 사용할 때 사용되는 임시 설치 암호의 유형입니다.
+

TIP: 모든 노드 또는 대부분의 노드가 동일한 유형의 임시 설치 암호를 사용하는 경우 전역 매개 변수 섹션에 형식을 지정합니다. 그런 다음 필요에 따라 개별 노드에 대해 다른 설정을 사용합니다. 예를 들어, * 사용자 정의 암호 사용 * 을 전역적으로 선택한 경우 * custom_temporary_password=<password> * 를 사용하여 각 노드의 암호를 설정할 수 있습니다.

+
* Temporary_password_type * 은 다음 중 하나일 수 있습니다.

+
** *노드 이름 사용*: 노드 이름은 임시 설치 암호로 사용됩니다.
** * 비밀번호 비활성화 * : 임시 설치 비밀번호가 사용되지 않습니다. 설치 문제를 디버깅하기 위해 VM에 액세스해야 하는 경우 를 참조하십시오 link:troubleshooting-installation-issues.html["설치 문제를 해결합니다"].
** * 사용자 정의 암호 사용 *: * custom_temporary_password=<password> * 에 제공된 값이 임시 설치 암호로 사용됩니다.
+

TIP: 필요한 경우 * Temporary_password_type * 매개 변수를 생략하고 * custom_Temporary_password=<password> * 만 지정할 수 있습니다.



* * CUSTOM_TEMENT_PASSWORD = <password> *
선택 사항. 설치 중에 이 VM에 액세스하고 SSH를 사용할 때 사용할 임시 암호입니다. Temporary_password_type * 이 * 노드 이름 사용 * 또는 * 암호 비활성화 * 로 설정된 경우 무시됩니다.




==== 노드별 매개 변수

각 노드는 구성 파일의 자체 섹션에 있습니다. 각 노드에는 다음과 같은 설정이 필요합니다.

* 섹션 헤드는 그리드 관리자에 표시될 노드 이름을 정의합니다. 노드에 대해 선택 사항인 node_name 매개 변수를 지정하여 이 값을 재정의할 수 있습니다.
* * node_type *: VM_Admin_Node, VM_Storage_Node, VM_Archive_Node 또는 VM_API_Gateway_Node
* * GRID_NETWORK_IP *: 그리드 네트워크의 노드에 대한 IP 주소입니다.
* * admin_network_ip *: 관리 네트워크의 노드에 대한 IP 주소입니다. 노드가 Admin Network에 연결되어 있고 admin_network_Config가 static으로 설정된 경우에만 필요합니다.
* * client_network_ip *: 클라이언트 네트워크의 노드에 대한 IP 주소입니다. 노드가 클라이언트 네트워크에 연결되어 있고 이 노드의 client_network_Config가 static으로 설정된 경우에만 필요합니다.
* * admin_IP *: 그리드 네트워크의 기본 관리 노드에 대한 IP 주소입니다. 기본 관리 노드에 대해 GRID_NETWORK_IP로 지정하는 값을 사용합니다. 이 매개 변수를 생략하면 노드가 mDNS를 사용하여 운영 관리 노드 IP를 검색합니다. 자세한 내용은 을 참조하십시오 link:how-grid-nodes-discover-primary-admin-node.html["그리드 노드가 기본 관리자 노드를 검색하는 방법"].
+

NOTE: admin_ip 매개 변수는 기본 관리 노드에 대해 무시됩니다.

* 전역적으로 설정되지 않은 모든 매개변수. 예를 들어, 노드가 관리 네트워크에 연결되어 있고 admin_network 매개 변수를 전역으로 지정하지 않은 경우 노드에 대해 이러한 매개 변수를 지정해야 합니다.


.기본 관리자 노드
기본 관리 노드에는 다음과 같은 추가 설정이 필요합니다.

* * node_type *: vm_Admin_Node
* * admin_role *: 기본


이 예제 항목은 세 네트워크 모두에 있는 기본 관리 노드에 대한 것입니다.

[listing]
----
[DC1-ADM1]
  ADMIN_ROLE = Primary
  NODE_TYPE = VM_Admin_Node

  GRID_NETWORK_IP = 10.1.0.2
  ADMIN_NETWORK_IP = 10.3.0.2
  CLIENT_NETWORK_IP = 10.4.0.2
----
기본 관리 노드에는 다음과 같은 추가 설정이 선택 사항입니다.

* * 디스크 *: 기본적으로 감사 및 데이터베이스 사용을 위해 관리자 노드에 두 개의 추가 200GB 하드 디스크가 할당됩니다. disk 매개 변수를 사용하여 이러한 설정을 늘릴 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: 관리 노드의 경우 인스턴스는 항상 2가 되어야 합니다.

.스토리지 노드
스토리지 노드에는 다음과 같은 추가 설정이 필요합니다.

* * node_type *: vm_storage_Node
+
이 예제 항목은 그리드 및 관리 네트워크에 있지만 클라이언트 네트워크에 없는 스토리지 노드에 대한 것입니다. 이 노드는 admin_ip 설정을 사용하여 그리드 네트워크에서 기본 관리 노드의 IP 주소를 지정합니다.

+
[listing]
----
[DC1-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.0.3
  ADMIN_NETWORK_IP = 10.3.0.3

  ADMIN_IP = 10.1.0.2
----
+
이 두 번째 예제 항목은 고객의 엔터프라이즈 네트워킹 정책에서 포트 80 또는 443을 사용하여 스토리지 노드에 액세스할 수 있다고 명시하는 클라이언트 네트워크의 스토리지 노드에 대한 것입니다. 예제 구성 파일은 port_remap을 사용하여 스토리지 노드가 포트 443에서 S3 메시지를 보내고 받을 수 있도록 합니다.

+
[listing]
----
[DC2-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3
  CLIENT_NETWORK_IP = 10.4.1.3
  PORT_REMAP = client/tcp/18082/443

  ADMIN_IP = 10.1.0.2
----
+
마지막 예에서는 포트 22에서 포트 3022로 ssh 트래픽에 대한 대칭 재매핑을 생성하지만 인바운드 및 아웃바운드 트래픽에 대한 값을 명시적으로 설정합니다.

+
[listing]
----
[DC1-S3]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3

  PORT_REMAP = grid/tcp/22/3022
  PORT_REMAP_INBOUND = grid/tcp/3022/22

  ADMIN_IP = 10.1.0.2
----


스토리지 노드의 경우 다음 추가 설정은 선택 사항입니다.

* * disk *: 기본적으로 스토리지 노드에는 RangeDB 사용을 위해 3 개의 4TB 디스크가 할당됩니다. 디스크 매개 변수를 사용하여 이러한 설정을 늘릴 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
DISK = INSTANCES=16, CAPACITY=4096
----


.아카이브 노드
아카이브 노드에 대해 다음 추가 설정이 필요합니다.

* * node_type *: vm_Archive_Node


이 예제 항목은 그리드 및 관리 네트워크에 있지만 클라이언트 네트워크에 없는 아카이브 노드에 대한 것입니다.

[listing]
----
[DC1-ARC1]
  NODE_TYPE = VM_Archive_Node

  GRID_NETWORK_IP = 10.1.0.4
  ADMIN_NETWORK_IP = 10.3.0.4

  ADMIN_IP = 10.1.0.2
----
.게이트웨이 노드
게이트웨이 노드에는 다음과 같은 추가 설정이 필요합니다.

* * node_type *: vm_api_Gateway


이 예제 항목은 세 네트워크 모두에서 게이트웨이 노드의 예입니다. 이 예에서는 구성 파일의 전역 섹션에 클라이언트 네트워크 매개 변수가 지정되지 않아 노드에 대해 지정해야 합니다.

[listing]
----
[DC1-G1]
  NODE_TYPE = VM_API_Gateway

  GRID_NETWORK_IP = 10.1.0.5
  ADMIN_NETWORK_IP = 10.3.0.5

  CLIENT_NETWORK_CONFIG = STATIC
  CLIENT_NETWORK_TARGET = SG-Client-Network
  CLIENT_NETWORK_MASK = 255.255.255.0
  CLIENT_NETWORK_GATEWAY = 10.4.0.1
  CLIENT_NETWORK_IP = 10.4.0.5

  ADMIN_IP = 10.1.0.2
----
.운영 관리자 노드가 아닌 노드
운영 관리자 노드가 아닌 경우 다음과 같은 추가 설정이 필요합니다.

* * node_type *: vm_Admin_Node
* * admin_role *: Non-Primary


이 예제 항목은 클라이언트 네트워크에 없는 비 기본 관리 노드에 대한 것입니다.

[listing]
----
[DC2-ADM1]
  ADMIN_ROLE = Non-Primary
  NODE_TYPE = VM_Admin_Node

  GRID_NETWORK_TARGET = SG-Grid-Network
  GRID_NETWORK_IP = 10.1.0.6
  ADMIN_NETWORK_IP = 10.3.0.6

  ADMIN_IP = 10.1.0.2
----
다음 추가 설정은 운영 관리자 노드가 아닌 경우 선택 사항입니다.

* * 디스크 *: 기본적으로 감사 및 데이터베이스 사용을 위해 관리자 노드에 두 개의 추가 200GB 하드 디스크가 할당됩니다. disk 매개 변수를 사용하여 이러한 설정을 늘릴 수 있습니다. 예를 들면 다음과 같습니다.
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: 관리 노드의 경우 인스턴스는 항상 2가 되어야 합니다.



== Bash 스크립트를 실행합니다

를 사용할 수 있습니다 `deploy-vsphere-ovftool.sh` VMware vSphere에서 StorageGRID 노드 배포를 자동화하기 위해 수정한 Bash 스크립트 및 deploy-vsphere-ovftool.ini 구성 파일입니다.

.시작하기 전에
* 사용자 환경에 대한 deploy-vsphere-ovftool.ini 구성 파일을 만들었습니다.


도움말 명령을 입력하여 Bash 스크립트에서 사용할 수 있는 도움말을 사용할 수 있습니다 (`-h/--help`)를 클릭합니다. 예를 들면 다음과 같습니다.

[listing]
----
./deploy-vsphere-ovftool.sh -h
----
또는

[listing]
----
./deploy-vsphere-ovftool.sh --help
----
.단계
. Bash 스크립트를 실행하기 위해 사용 중인 Linux 시스템에 로그인합니다.
. 설치 아카이브를 추출한 디렉토리로 변경합니다.
+
예를 들면 다음과 같습니다.

+
[listing]
----
cd StorageGRID-Webscale-version/vsphere
----
. 모든 그리드 노드를 배포하려면 환경에 적합한 옵션을 사용하여 Bash 스크립트를 실행합니다.
+
예를 들면 다음과 같습니다.

+
[listing]
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd ./deploy-vsphere-ovftool.ini
----
. 오류로 인해 그리드 노드를 배포하지 못한 경우 오류를 해결하고 해당 노드에 대해서만 Bash 스크립트를 다시 실행합니다.
+
예를 들면 다음과 같습니다.

+
[listing]
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd --single-node="DC1-S3" ./deploy-vsphere-ovftool.ini
----


각 노드의 상태가 "Passed"이면 배포가 완료됩니다.

[listing]
----
Deployment Summary
+-----------------------------+----------+----------------------+
| node                        | attempts | status               |
+-----------------------------+----------+----------------------+
| DC1-ADM1                    |        1 | Passed               |
| DC1-G1                      |        1 | Passed               |
| DC1-S1                      |        1 | Passed               |
| DC1-S2                      |        1 | Passed               |
| DC1-S3                      |        1 | Passed               |
+-----------------------------+----------+----------------------+
----


== StorageGRID의 구성을 자동화합니다

그리드 노드를 구축한 후 StorageGRID 시스템 구성을 자동화할 수 있습니다.

.시작하기 전에
* 설치 아카이브에서 다음 파일의 위치를 알고 있습니다.


[cols="1a,1a"]
|===
| 파일 이름 | 설명 


| configure-storagegrid.py  a| 
구성을 자동화하는 데 사용되는 Python 스크립트입니다



| configure -StorageGrid.sample.json  a| 
스크립트와 함께 사용할 예제 구성 파일



| configure -StorageGrid.blank.json을 지정합니다  a| 
스크립트에 사용할 빈 구성 파일입니다

|===
* 을(를) 만들었습니다 `configure-storagegrid.json` 구성 파일. 이 파일을 작성하려면 예제 구성 파일을 수정할 수 있습니다 (`configure-storagegrid.sample.json`) 또는 빈 구성 파일 (`configure-storagegrid.blank.json`)를 클릭합니다.


를 사용할 수 있습니다 `configure-storagegrid.py` Python 스크립트와 `configure-storagegrid.json` StorageGRID 시스템 구성을 자동화하는 구성 파일입니다.


NOTE: 그리드 관리자 또는 설치 API를 사용하여 시스템을 구성할 수도 있습니다.

.단계
. Python 스크립트를 실행하기 위해 사용 중인 Linux 시스템에 로그인합니다.
. 설치 아카이브를 추출한 디렉토리로 변경합니다.
+
예를 들면 다음과 같습니다.

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
위치 `platform` debs, rpms 또는 vSphere입니다.

. Python 스크립트를 실행하고 생성한 구성 파일을 사용합니다.
+
예를 들면 다음과 같습니다.

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.결과
복구 패키지 `.zip` 파일은 구성 프로세스 중에 생성되며 설치 및 구성 프로세스를 실행 중인 디렉토리에 다운로드됩니다. 하나 이상의 그리드 노드에 장애가 발생할 경우 StorageGRID 시스템을 복구할 수 있도록 복구 패키지 파일을 백업해야 합니다. 예를 들어, 안전한 백업 네트워크 위치 및 안전한 클라우드 저장소 위치에 복사합니다.


CAUTION: 복구 패키지 파일은 StorageGRID 시스템에서 데이터를 가져오는 데 사용할 수 있는 암호화 키와 암호가 포함되어 있으므로 보안을 유지해야 합니다.

임의 암호를 생성해야 한다고 지정한 경우 를 엽니다 `Passwords.txt` 파일을 만들고 StorageGRID 시스템에 액세스하는 데 필요한 암호를 찾습니다.

[listing]
----
######################################################################
##### The StorageGRID "recovery package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
확인 메시지가 표시되면 StorageGRID 시스템이 설치 및 구성됩니다.

[listing]
----
StorageGRID has been configured and installed.
----
.관련 정보
link:navigating-to-grid-manager.html["그리드 관리자로 이동합니다"]

link:overview-of-installation-rest-api.html["설치 REST API 개요"]
