---
permalink: admin/archive-node-configuration-and-operation.html 
sidebar: sidebar 
keywords: archive node configuration 
summary: StorageGRID 시스템은 아카이브 노드를 무기한으로 저장되고 항상 액세스할 수 있는 위치로 관리합니다. 
---
= 아카이브 노드 구성 및 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템은 아카이브 노드를 무기한으로 저장되고 항상 액세스할 수 있는 위치로 관리합니다.

오브젝트가 수집되면 StorageGRID 시스템에 정의된 ILM(정보 라이프사이클 관리) 규칙에 따라 아카이브 노드를 포함하여 모든 필요한 위치에 복사본이 생성됩니다. 아카이브 노드는 TSM 서버에 대한 클라이언트 역할을 하며 TSM 클라이언트 라이브러리는 StorageGRID 소프트웨어 설치 프로세스에 의해 아카이브 노드에 설치됩니다. 스토리지의 아카이브 노드에 대한 객체 데이터는 수신된 TSM 서버에 직접 저장됩니다. 아카이브 노드는 TSM 서버에 저장하기 전에 객체 데이터를 스테이징하지 않으며 객체 집계를 수행하지 않습니다. 그러나 데이터 속도가 필요한 경우 아카이브 노드는 하나의 트랜잭션에서 TSM 서버에 여러 복제본을 제출할 수 있습니다.

아카이브 노드가 TSM 서버에 객체 데이터를 저장한 후 TSM 서버에서 해당 수명주기/보존 정책을 사용하여 객체 데이터를 관리합니다. 이러한 보존 정책은 아카이브 노드의 작업과 호환되도록 정의해야 합니다. 즉, 아카이브 노드에서 저장한 개체 데이터는 보관 노드에서 삭제하지 않는 한 영구적으로 저장해야 하며 항상 아카이브 노드에서 액세스할 수 있어야 합니다.

StorageGRID 시스템의 ILM 규칙과 TSM 서버의 수명주기/보존 정책 간에는 연결이 없습니다. 각 개체는 서로 독립적으로 작동하지만, 각 개체는 StorageGRID 시스템으로 수집되므로 TSM 관리 클래스를 할당할 수 있습니다. 이 관리 클래스는 객체 데이터와 함께 TSM 서버로 전달됩니다. 여러 객체 유형에 서로 다른 관리 클래스를 할당하면 TSM 서버가 서로 다른 스토리지 풀에 객체 데이터를 배치하도록 구성하거나 필요에 따라 다른 마이그레이션 또는 보존 정책을 적용하도록 구성할 수 있습니다. 예를 들어 데이터베이스 백업으로 식별된 개체(최신 데이터로 덮어쓸 수 있는 임시 콘텐츠)는 응용 프로그램 데이터(영구적으로 보존해야 하는 고정 콘텐츠)와 다르게 처리될 수 있습니다.

아카이브 노드는 새 TSM 서버 또는 기존 TSM 서버와 통합할 수 있으며 전용 TSM 서버가 필요하지 않습니다. TSM 서버의 크기가 최대 예상 로드에 맞게 적절히 지정되면 TSM 서버를 다른 클라이언트와 공유할 수 있습니다. TSM은 아카이브 노드와 분리된 서버 또는 가상 머신에 설치해야 합니다.

동일한 TSM 서버에 쓰기 위해 아카이브 노드를 두 개 이상 구성할 수 있지만 아카이브 노드가 서로 다른 데이터 세트를 TSM 서버에 쓰는 경우에만 이 구성이 권장됩니다. 각 아카이브 노드가 동일한 객체 데이터의 복제본을 아카이브에 쓸 때 동일한 TSM 서버에 쓰기 위해 아카이브 노드를 두 개 이상 구성하는 것은 권장되지 않습니다. 두 복제본 모두 독립적인 중복 객체 데이터 복제본에 대해 단일 장애 지점(TSM 서버)에 해당합니다.

아카이브 노드는 TSM의 HSM(Hierarchical Storage Management) 구성 요소를 사용하지 않습니다.
