---
permalink: admin/archiving-to-tape-through-tsm-middleware.html 
sidebar: sidebar 
keywords: tivoli storage manager, tsm server, archive node, tape 
summary: '테이프 라이브러리를 포함하여 랜덤 또는 순차 액세스 스토리지 디바이스에 오브젝트 데이터를 저장하고 검색하기 위한 논리 인터페이스를 제공하는 TSM(Tivoli Storage Manager) 서버를 타겟으로 하는 아카이브 노드를 구성할 수 있습니다.' 
---
= TSM 미들웨어를 통해 테이프로 아카이빙
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테이프 라이브러리를 포함하여 랜덤 또는 순차 액세스 스토리지 디바이스에 오브젝트 데이터를 저장하고 검색하기 위한 논리 인터페이스를 제공하는 TSM(Tivoli Storage Manager) 서버를 대상으로 아카이브 노드를 구성할 수 있습니다.

아카이브 노드의 ARC 서비스는 TSM 서버에 대한 클라이언트 역할을 하며 Tivoli Storage Manager를 아카이빙 스토리지 시스템과 통신하는 미들웨어로 사용합니다.

[CAUTION]
====
아카이브 노드에 대한 지원은 더 이상 사용되지 않으며 향후 릴리즈에서 제거될 예정입니다. S3 API를 통해 아카이브 노드에서 외부 아카이브 스토리지 시스템으로 오브젝트를 이동한 후 ILM 클라우드 스토리지 풀로 대체되었으며 더 많은 기능을 제공합니다.

Cloud Tiering - S3(Simple Storage Service) 옵션도 더 이상 사용되지 않습니다. 현재 이 옵션으로 아카이브 노드를 사용 중인 경우 link:../admin/migrating-objects-from-cloud-tiering-s3-to-cloud-storage-pool.html["오브젝트를 클라우드 스토리지 풀로 마이그레이션합니다"] 대신

또한 StorageGRID 11.7 이하의 활성 ILM 정책에서 아카이브 노드를 제거해야 합니다. 아카이브 노드에 저장된 오브젝트 데이터를 제거하면 향후 업그레이드가 간소화됩니다. 을 참조하십시오 link:../ilm/working-with-ilm-rules-and-ilm-policies.html["ILM 규칙 및 ILM 정책 작업"].

====


== TSM 관리 클래스

TSM 미들웨어에 의해 정의된 관리 클래스는 TSM의 백업 및 아카이브 작업이 작동하는 방식을 요약하고 TSM 서버에 의해 적용되는 콘텐츠에 대한 규칙을 지정하는 데 사용할 수 있습니다. 이러한 규칙은 StorageGRID 시스템의 ILM 정책과 독립적으로 작동하며, 객체가 영구적으로 저장되고 아카이브 노드에서 검색할 수 있도록 항상 사용 가능한 StorageGRID 시스템의 요구 사항과 일치해야 합니다. 아카이브 노드에서 TSM 서버로 객체 데이터를 전송한 후 TSM 서버에서 관리하는 테이프에 객체 데이터를 저장하는 동안 TSM 수명주기 및 보존 규칙이 적용됩니다.

TSM 관리 클래스는 아카이브 노드에서 TSM 서버로 객체가 전송된 후 데이터 위치 또는 보존에 대한 규칙을 적용하기 위해 TSM 서버에서 사용됩니다. 예를 들어, 데이터베이스 백업으로 식별된 객체(최신 데이터로 덮어쓸 수 있는 임시 컨텐츠)는 애플리케이션 데이터(무기한으로 보존되어야 하는 고정 컨텐츠)와 다르게 처리될 수 있습니다.
