---
permalink: admin/changing-network-options-object-encryption.html 
sidebar: sidebar 
keywords: enable http, storage node connections 
summary: 네트워크 및 개체 보안을 구성하여 저장된 개체를 암호화하고, 특정 S3 및 Swift 요청을 방지하거나, 스토리지 노드에 대한 클라이언트 연결이 HTTPS 대신 HTTP를 사용하도록 허용할 수 있습니다. 
---
= 네트워크 및 개체 보안을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
네트워크 및 개체 보안을 구성하여 저장된 개체를 암호화하고, 특정 S3 및 Swift 요청을 방지하거나, 스토리지 노드에 대한 클라이언트 연결이 HTTPS 대신 HTTP를 사용하도록 허용할 수 있습니다.



== 저장된 오브젝트 암호화

저장된 오브젝트 암호화를 통해 S3를 통해 수집된 모든 오브젝트 데이터를 암호화할 수 있습니다. 기본적으로 저장된 개체는 암호화되지 않지만 AES‐128 또는 AES‐256 암호화 알고리즘을 사용하여 개체를 암호화하도록 선택할 수 있습니다. 이 설정을 활성화하면 새로 수집된 모든 객체가 암호화되지만 기존 저장된 객체는 변경되지 않습니다. 암호화를 사용하지 않도록 설정하면 현재 암호화된 개체는 암호화된 상태로 유지되지만 새로 수집된 개체는 암호화되지 않습니다.

저장된 오브젝트 암호화 설정은 버킷 레벨 또는 오브젝트 레벨 암호화로 암호화되지 않은 S3 오브젝트에만 적용됩니다.

StorageGRID 암호화 방법에 대한 자세한 내용은 를 참조하십시오 link:../admin/reviewing-storagegrid-encryption-methods.html["StorageGRID 암호화 방법을 검토합니다"].



== 클라이언트 수정을 방지합니다

클라이언트 수정 방지 는 시스템 전체 설정입니다. 클라이언트 수정 방지 * 옵션을 선택하면 다음 요청이 거부됩니다.



=== S3 REST API

* DeleteBucket 요청
* 기존 오브젝트의 데이터, 사용자 정의 메타데이터 또는 S3 오브젝트 태그 지정을 수정하는 요청




=== Swift REST API

* 컨테이너 요청을 삭제합니다
* 기존 객체 수정 요청. 예를 들어, 덮어쓰기, 삭제, 메타데이터 업데이트 등의 작업이 거부됩니다.




== 스토리지 노드 연결에 대해 HTTP를 설정합니다

기본적으로 클라이언트 애플리케이션은 스토리지 노드에 대한 직접 연결에 HTTPS 네트워크 프로토콜을 사용합니다. 비프로덕션 그리드를 테스트할 때와 같이 이러한 연결에 대해 HTTP를 선택적으로 활성화할 수 있습니다.

S3 및 Swift 클라이언트가 스토리지 노드에 직접 HTTP 연결을 해야 하는 경우에만 스토리지 노드 연결에 HTTP를 사용합니다. HTTPS 연결만 사용하는 클라이언트 또는 로드 밸런서 서비스에 연결된 클라이언트(에서 할 수 있기 때문에)에는 이 옵션을 사용할 필요가 없습니다 link:../admin/configuring-load-balancer-endpoints.html["각 로드 밸런서 엔드포인트를 구성합니다"] HTTP 또는 HTTPS 사용).

을 참조하십시오 link:summary-ip-addresses-and-ports-for-client-connections.html["요약: 클라이언트 연결을 위한 IP 주소 및 포트"] HTTP 또는 HTTPS를 사용하여 스토리지 노드에 연결할 때 사용하는 S3 및 Swift 포트에 대해 알아봅니다.



== 옵션을 선택합니다

.시작하기 전에
* 를 사용하여 그리드 관리자에 로그인했습니다 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"].
* 루트 액세스 권한이 있습니다.


.단계
. 구성 * > * 보안 * > * 보안 설정 * 을 선택합니다.
. Network and objects * 탭을 선택합니다.
. 저장된 개체 암호화의 경우 저장된 개체를 암호화하지 않으려면 * 없음 * (기본값) 설정을 사용하거나 * AES-128 * 또는 * AES-256 * 을 선택하여 저장된 개체를 암호화합니다.
. S3 및 Swift 클라이언트가 특정 요청을 하지 못하게 하려면 * 클라이언트 수정 방지 * 를 선택합니다(선택 사항).
+

NOTE: 이 설정을 변경하면 새 설정을 적용하는 데 약 1분이 걸립니다. 구성된 값이 성능 및 확장을 위해 캐싱됩니다.

. 클라이언트가 스토리지 노드에 직접 접속하고 HTTP 연결을 사용하려는 경우 선택적으로 * 스토리지 노드 연결에 HTTP 사용 * 을 선택합니다.
+

NOTE: 요청이 암호화되지 않은 상태로 전송되므로 프로덕션 그리드에 대해 HTTP를 설정할 때는 주의해야 합니다.

. 저장 * 을 선택합니다.

