---
permalink: admin/configuration-best-practices.html 
sidebar: sidebar 
keywords: tsm configuration, tivoli storage manager, archive to tape 
summary: TSM 서버를 사이징하고 구성할 때는 아카이브 노드와 함께 작동하도록 최적화하기 위해 이를 최적화하는 모범 사례를 적용해야 합니다. 
---
= 구성 모범 사례
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
TSM 서버를 사이징하고 구성할 때는 아카이브 노드와 함께 작동하도록 최적화하기 위해 이를 최적화하는 모범 사례를 적용해야 합니다.

TSM 서버를 사이징하고 구성할 때는 다음 요소를 고려해야 합니다.

* 아카이브 노드는 TSM 서버에 저장하기 전에 객체를 집계하지 않기 때문에 아카이브 노드에 기록될 모든 객체에 대한 참조를 보유할 수 있도록 TSM 데이터베이스의 크기를 조정해야 합니다.
* 아카이브 노드 소프트웨어는 테이프 또는 기타 이동식 미디어에 직접 개체를 쓰는 데 수반되는 지연 시간을 허용할 수 없습니다. 따라서 이동식 미디어를 사용할 때마다 아카이브 노드에서 저장한 데이터의 초기 스토리지를 위해 TSM 서버를 디스크 스토리지 풀로 구성해야 합니다.
* 이벤트 기반 보존을 사용하려면 TSM 보존 정책을 구성해야 합니다. 아카이브 노드는 생성 기반 TSM 보존 정책을 지원하지 않습니다. 보존 정책에서 retmin=0 및 retver=0의 권장 설정을 사용합니다. 보존 정책은 보관 노드가 보존 이벤트를 트리거할 때 보존이 시작되고 그 후 0일 동안 유지됨을 나타냅니다. 그러나 retmin 및 retver에 대한 이러한 값은 선택 사항입니다.


데이터를 테이프 풀로 마이그레이션하도록 디스크 풀을 구성해야 합니다. 즉, 테이프 풀은 디스크 풀의 NXTSTOOL이어야 합니다. 테이프 풀은 두 풀에 동시에 쓰는 디스크 풀의 복제 풀로 구성해서는 안 됩니다. 즉, 테이프 풀은 디스크 풀의 COPYSTGPOOL이 될 수 없습니다. 아카이브 노드 데이터를 포함하는 테이프의 오프라인 복사본을 생성하려면 아카이브 노드 데이터에 사용되는 테이프 풀의 복사본 풀인 두 번째 테이프 풀을 사용하여 TSM 서버를 구성합니다.
