---
permalink: admin/configuring-audit-client-access.html 
sidebar: sidebar 
keywords: audit client, ams, audit management service 
summary: 'AMS(감사 관리 시스템) 서비스를 통해 관리 노드는 감사 공유를 통해 사용 가능한 로그 파일에 모든 감사 시스템 이벤트를 기록하며, 이 로그 파일은 설치 시 각 관리 노드에 추가됩니다. 감사 공유는 읽기 전용 공유로 자동 설정됩니다.' 
---
= NFS에 대한 감사 클라이언트 액세스를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AMS(감사 관리 시스템) 서비스를 통해 관리 노드는 감사 공유를 통해 사용 가능한 로그 파일에 모든 감사 시스템 이벤트를 기록하며, 이 로그 파일은 설치 시 각 관리 노드에 추가됩니다. 감사 공유는 읽기 전용 공유로 자동 설정됩니다.


NOTE: NFS에 대한 지원은 더 이상 사용되지 않으며 향후 릴리즈에서 제거될 예정입니다.

감사 로그에 액세스하려면 NFS에 대한 감사 공유에 대한 클라이언트 액세스를 구성할 수 있습니다. 아니면 가능합니다 link:../monitor/considerations-for-external-syslog-server.html["외부 syslog 서버를 사용합니다"].

StorageGRID 시스템은 감사 메시지를 로그 파일에 쓰기 전에 손실을 방지하기 위해 긍정 승인을 사용합니다. AMS 서비스 또는 중간 감사 릴레이 서비스가 해당 제어 권한을 확인할 때까지 메시지는 서비스 대기 상태로 유지됩니다. 자세한 내용은 을 참조하십시오 link:../audit/index.html["감사 로그를 검토합니다"].

.시작하기 전에
* 을(를) 보유하고 있습니다 `Passwords.txt` 루트/관리자 암호가 있는 파일입니다.
* 을(를) 보유하고 있습니다 `Configuration.txt` 파일(복구 패키지에서 사용 가능).
* 감사 클라이언트가 NFS 버전 3(NFSv3)을 사용하고 있습니다.


.이 작업에 대해
감사 메시지를 검색할 StorageGRID 배포의 각 관리자 노드에 대해 이 절차를 수행합니다.

.단계
. 기본 관리자 노드에 로그인합니다.
+
.. 다음 명령을 입력합니다. `ssh admin@_primary_Admin_Node_IP_`
.. 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.
.. 루트로 전환하려면 다음 명령을 입력합니다. `su -`
.. 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 에서 변경됩니다 `$` 를 선택합니다 `#`.



. 모든 서비스의 상태가 실행 중 또는 확인인지 확인합니다. 입력: `storagegrid-status`
+
실행 중 또는 확인으로 나열되지 않은 서비스가 있는 경우 계속하기 전에 문제를 해결합니다.

. 명령줄로 돌아갑니다. Ctrl * + * C * 를 누릅니다.
. NFS 구성 유틸리티를 시작합니다. 입력: `config_nfs.rb`
+
[listing]
----

-----------------------------------------------------------------
| Shares               | Clients              | Config          |
-----------------------------------------------------------------
| add-audit-share      | add-ip-to-share      | validate-config |
| enable-disable-share | remove-ip-from-share | refresh-config  |
|                      |                      | help            |
|                      |                      | exit            |
-----------------------------------------------------------------
----
. 감사 클라이언트를 추가합니다. `add-audit-share`
+
.. 메시지가 표시되면 감사 공유의 감사 클라이언트의 IP 주소 또는 IP 주소 범위를 입력합니다. `client_IP_address`
.. 메시지가 표시되면 * Enter * 를 누릅니다.


. 둘 이상의 감사 클라이언트가 감사 공유에 액세스할 수 있는 경우 추가 사용자의 IP 주소를 추가합니다. `add-ip-to-share`
+
.. 감사 공유의 번호를 입력합니다. `_audit_share_number_`
.. 메시지가 표시되면 감사 공유의 감사 클라이언트의 IP 주소 또는 IP 주소 범위를 입력합니다. `_client_IP_address_`
.. 메시지가 표시되면 * Enter * 를 누릅니다.
+
NFS 구성 유틸리티가 표시됩니다.

.. 감사 공유에 대한 액세스 권한이 있는 각 추가 감사 클라이언트에 대해 이러한 하위 단계를 반복합니다.


. 필요한 경우 구성을 확인합니다.
+
.. 다음을 입력합니다. `validate-config`
+
서비스가 확인 및 표시됩니다.

.. 메시지가 표시되면 * Enter * 를 누릅니다.
+
NFS 구성 유틸리티가 표시됩니다.

.. NFS 구성 유틸리티를 닫습니다. `exit`


. 다른 사이트에서 감사 공유를 사용하도록 설정해야 하는지 확인합니다.
+
** StorageGRID 배포가 단일 사이트인 경우 다음 단계로 이동합니다.
** StorageGRID 구축에 다른 사이트의 관리 노드가 포함되는 경우 필요에 따라 다음 감사 공유를 활성화합니다.
+
... 사이트의 관리 노드에 원격으로 로그인:
+
.... 다음 명령을 입력합니다. `ssh admin@_grid_node_IP_`
.... 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.
.... 루트로 전환하려면 다음 명령을 입력합니다. `su -`
.... 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.


... 이 단계를 반복하여 각 추가 관리 노드에 대한 감사 공유를 구성합니다.
... 원격 관리 노드에 대한 원격 보안 셸 로그인을 닫습니다. 입력: `exit`




. 명령 셸에서 로그아웃합니다. `exit`
+
NFS 감사 클라이언트는 IP 주소를 기반으로 감사 공유에 대한 액세스 권한이 부여됩니다. 공유에 IP 주소를 추가하여 새 NFS 감사 클라이언트에 감사 공유에 대한 액세스 권한을 부여하거나 IP 주소를 제거하여 기존 감사 클라이언트를 제거합니다.


