---
permalink: admin/manage-security.html 
sidebar: sidebar 
keywords: how to manage security 
summary: 그리드 관리자에서 다양한 보안 설정을 구성하여 StorageGRID 시스템을 보호할 수 있습니다. 
---
= 보안 관리: 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 관리자에서 다양한 보안 설정을 구성하여 StorageGRID 시스템을 보호할 수 있습니다.



== 암호화 관리

StorageGRID는 데이터 암호화를 위한 여러 옵션을 제공합니다. 당신은 해야 한다 link:reviewing-storagegrid-encryption-methods.html["사용 가능한 암호화 방법을 검토합니다"] 데이터 보호 요구사항을 충족하는 스토리지 결정



== 인증서를 관리합니다

가능합니다 link:using-storagegrid-security-certificates.html["서버 인증서를 구성하고 관리합니다"] 서버에 대한 클라이언트 또는 사용자 ID를 인증하는 데 사용되는 클라이언트 인증서 또는 HTTP 연결에 사용됩니다.



== 키 관리 서버를 구성합니다

를 사용합니다 link:kms-configuring.html["키 관리 서버입니다"] 어플라이언스를 데이터 센터에서 제거하더라도 StorageGRID 데이터를 보호할 수 있습니다. 어플라이언스 볼륨이 암호화된 후에는 노드에서 KMS와 통신할 수 없는 한 어플라이언스의 데이터에 액세스할 수 없습니다.


NOTE: 암호화 키 관리를 사용하려면 어플라이언스를 그리드에 추가하기 전에 설치 중에 각 어플라이언스에 대해 * 노드 암호화 * 설정을 활성화해야 합니다.



== 프록시 설정을 관리합니다

S3 플랫폼 서비스 또는 클라우드 스토리지 풀을 사용하는 경우 를 구성할 수 있습니다 link:configuring-storage-proxy-settings.html["스토리지 프록시 서버입니다"] 스토리지 노드 및 외부 S3 엔드포인트 간 HTTPS 또는 HTTP를 사용하여 AutoSupport 패키지를 보내는 경우 를 구성할 수 있습니다 link:configuring-admin-proxy-settings.html["관리 프록시 서버"] 관리 노드와 기술 지원 간



== 방화벽을 제어합니다

시스템의 보안을 강화하기 위해 에서 특정 포트를 열거나 닫아 StorageGRID 관리 노드에 대한 액세스를 제어할 수 있습니다 link:controlling-access-through-firewalls.html["외부 방화벽"]. 또한 노드를 구성하여 각 노드에 대한 네트워크 액세스를 제어할 수도 있습니다 link:manage-firewall-controls.html["내부 방화벽"]. 배포에 필요한 포트를 제외한 모든 포트에 대한 액세스를 차단할 수 있습니다.
