---
permalink: admin/migrating-data-into-storagegrid.html 
sidebar: sidebar 
keywords: data migration, move data into storagegrid 
summary: 대량의 데이터를 StorageGRID 시스템으로 마이그레이션하는 동시에 일상적인 작업을 위해 StorageGRID 시스템을 사용할 수 있습니다. 
---
= 데이터를 StorageGRID로 마이그레이션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
대량의 데이터를 StorageGRID 시스템으로 마이그레이션하는 동시에 일상적인 작업을 위해 StorageGRID 시스템을 사용할 수 있습니다.

이 가이드를 사용하여 대량의 데이터를 StorageGRID 시스템으로 마이그레이션할 계획을 수립합니다. 이 가이드는 데이터 마이그레이션의 일반적인 가이드가 아니며 마이그레이션을 수행하기 위한 자세한 단계는 포함되어 있지 않습니다. 이 섹션의 지침과 지침을 따라 일상적인 작업을 방해하지 않으면서 데이터가 StorageGRID 시스템으로 효율적으로 마이그레이션되고 마이그레이션된 데이터가 StorageGRID 시스템에서 적절하게 처리되도록 하십시오.



== StorageGRID 시스템의 용량을 확인합니다

대량의 데이터를 StorageGRID 시스템으로 마이그레이션하기 전에 StorageGRID 시스템에 예상되는 볼륨을 처리할 수 있는 디스크 용량이 있는지 확인하십시오.

StorageGRID 시스템에 아카이브 노드가 포함되어 있고 마이그레이션된 객체의 복제본이 니어라인 스토리지(예: 테이프)에 저장된 경우 아카이브 노드의 스토리지가 마이그레이션된 데이터의 예상 볼륨에 충분한 용량을 가지고 있는지 확인합니다.

용량 평가의 일환으로 마이그레이션할 객체의 데이터 프로파일을 살펴보고 필요한 디스크 용량을 계산합니다. StorageGRID 시스템의 디스크 용량을 모니터링하는 방법에 대한 자세한 내용은 을 참조하십시오 link:managing-storage-nodes.html["스토리지 노드 관리"] 및 의 지침을 참조하십시오 link:../monitor/index.html["StorageGRID 모니터링"].



== 마이그레이션된 데이터에 대한 ILM 정책을 결정합니다

StorageGRID 시스템의 ILM 정책은 복사본 수, 복사본이 저장되는 위치 및 복사본 보유 기간을 결정합니다. ILM 정책은 시간 경과에 따라 개체를 필터링하고 개체 데이터를 관리하는 방법을 설명하는 ILM 규칙 집합으로 구성되어 있습니다.

마이그레이션된 데이터의 사용 방법과 마이그레이션된 데이터의 요구 사항에 따라 일상적인 작업에 사용되는 ILM 규칙과 다른 마이그레이션 데이터에 대한 고유한 ILM 규칙을 정의할 수 있습니다. 예를 들어, 마이그레이션에 포함된 데이터에 대한 규정 요구사항과 일상적인 데이터 관리에 대한 규정 요구사항이 서로 다른 경우 다른 등급의 스토리지에 마이그레이션된 데이터의 복사본을 여러 개 만들어야 할 수 있습니다.

마이그레이션된 데이터와 일상적인 작업과 저장된 오브젝트 데이터를 고유하게 구분할 수 있는 경우 마이그레이션된 데이터에만 적용되는 규칙을 구성할 수 있습니다.

메타데이터 기준 중 하나를 사용하여 데이터 유형을 안정적으로 구분할 수 있는 경우, 이 기준을 사용하여 마이그레이션된 데이터에만 적용되는 ILM 규칙을 정의할 수 있습니다.

데이터 마이그레이션을 시작하기 전에 StorageGRID 시스템의 ILM 정책과 마이그레이션 데이터에 적용되는 방법을 이해하고 ILM 정책에 대한 모든 변경 사항을 적용 및 테스트해야 합니다. 을 참조하십시오 link:../ilm/index.html["ILM을 사용하여 개체를 관리합니다"].


CAUTION: 잘못 지정된 ILM 정책으로 인해 복구할 수 없는 데이터 손실이 발생할 수 있습니다. ILM 정책을 활성화하기 전에 변경한 모든 내용을 주의 깊게 검토하여 정책이 의도한 대로 작동하는지 확인합니다.



== 마이그레이션이 운영에 미치는 영향을 평가합니다

StorageGRID 시스템은 오브젝트 스토리지 및 검색을 위한 효율적인 작업을 제공하고 오브젝트 데이터 및 메타데이터의 중복 복사본을 지속적으로 생성하여 데이터 손실로부터 데이터를 완벽하게 보호하도록 설계되었습니다.

그러나 이 가이드의 지침에 따라 데이터 마이그레이션을 신중하게 관리하여 일상적인 시스템 운영에 영향을 주거나, 극단적인 경우 StorageGRID 시스템 장애 시 데이터가 손실될 위험이 있습니다.

대량의 데이터를 마이그레이션하면 시스템에 추가 부하가 걸린 것입니다. StorageGRID 시스템이 로드가 많은 경우 객체를 저장하고 검색하는 요청에 더 느리게 응답합니다. 이로 인해 일상적인 작업에 필수적인 저장 및 검색 요청이 방해를 받을 수 있습니다. 마이그레이션으로 인해 다른 운영 문제가 발생할 수도 있습니다. 예를 들어, 스토리지 노드의 용량이 거의 다 되면 배치 수집으로 인한 과중한 간헐적 로드로 인해 스토리지 노드가 읽기 전용과 읽기-쓰기 간에 순환되어 알림을 생성할 수 있습니다.

로드가 많은 경우 큐는 StorageGRID 시스템에서 수행하는 다양한 작업에 대해 개발되어 오브젝트 데이터 및 메타데이터의 완전한 이중화를 보장할 수 있습니다.

마이그레이션 중에 StorageGRID 시스템을 안전하고 효율적으로 운영할 수 있도록 이 문서의 지침에 따라 데이터 마이그레이션을 신중하게 관리해야 합니다. 데이터를 마이그레이션할 때는 오브젝트를 일괄적으로 수집하거나 지속적으로 스로틀로 인제스트합니다. 그런 다음 StorageGRID 시스템을 지속적으로 모니터링하여 다양한 속성 값을 초과하지 않는지 확인합니다.



== 데이터 마이그레이션 예약 및 모니터링

필요한 기간 내에 ILM 정책에 따라 데이터를 배치할 수 있도록 데이터 마이그레이션을 예약하고 모니터링해야 합니다.



=== 데이터 마이그레이션을 예약합니다

핵심 운영 시간 중에는 데이터 마이그레이션을 하지 마십시오. 시스템 사용량이 적은 야간, 주말 및 기타 시간으로 데이터 마이그레이션을 제한합니다.

가능한 경우 활동이 많은 기간 동안에는 데이터 마이그레이션을 예약하지 마십시오. 그러나 높은 활동 기간을 완전히 피하는 것이 실용적이지 않은 경우에는 관련 특성을 면밀히 모니터링하고 허용 가능한 값을 초과하는 경우 조치를 취하는 한 계속 진행하는 것이 안전합니다.



=== 데이터 마이그레이션을 모니터링합니다

이 표에는 데이터 마이그레이션 중에 모니터링해야 하는 속성과 이러한 특성이 나타내는 문제가 나열되어 있습니다.

트래픽 분류 정책을 사용하여 수집 임계치를 조절할 경우, 다음 표에 설명된 통계와 함께 관찰된 비율을 모니터링하고 필요한 경우 제한을 줄일 수 있습니다.

[cols="1a,2a"]
|===
| 모니터링 | 설명 


 a| 
ILM 평가를 기다리는 개체의 수입니다
 a| 
. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다.
. 배포 * > * 개요 * > * 기본 * 을 선택합니다.
. ILM 활동 섹션에서 다음 특성에 대해 표시된 개체 수를 모니터링합니다.
+
** * Awaiting-all(XQUZ) *: ILM 평가를 기다리는 총 개체 수.
** * Awaiting-Client(XCQZ) *: 클라이언트 작업에서 ILM 평가를 기다리는 총 오브젝트 수(예: 수집).


. 이러한 속성 중 하나에 대해 표시되는 오브젝트 수가 100,000개를 초과할 경우 개체의 수집 속도를 조절하여 StorageGRID 시스템의 로드를 줄입니다.




 a| 
타겟 아카이브 시스템의 스토리지 용량
 a| 
ILM 정책이 마이그레이션된 데이터의 복사본을 대상 아카이브 스토리지 시스템(테이프 또는 클라우드)에 저장하는 경우 대상 아카이브 스토리지 시스템의 용량을 모니터링하여 마이그레이션된 데이터에 충분한 용량이 있는지 확인하십시오.



 a| 
* Archive Node * > * ARC * > * Store *
 a| 
ARVF(Store Failures) * 속성에 대한 알람이 트리거되면 대상 아카이브 스토리지 시스템의 용량이 한계에 도달했을 수 있습니다. 대상이 되는 아카이브 스토리지 시스템을 확인하고 알람을 트리거한 문제를 모두 해결합니다.

|===