---
permalink: admin/storage-node-configuration-settings.html 
sidebar: sidebar 
keywords: storage node, configuration settings, counters 
summary: '각 스토리지 노드는 여러 가지 구성 설정과 카운터를 사용합니다. 현재 설정을 보거나 카운터를 재설정하여 경보를 지워야 할 수도 있습니다.\(기존 시스템\)' 
---
= 스토리지 노드 구성 설정입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
각 스토리지 노드는 여러 가지 구성 설정과 카운터를 사용합니다. 현재 설정을 보거나 카운터를 재설정하여 알람을 소거해야 할 수 있습니다(기존 시스템).


CAUTION: 설명서에 구체적으로 명시된 경우를 제외하고 스토리지 노드 구성 설정을 수정하기 전에 기술 지원 부서에 문의해야 합니다. 필요에 따라 이벤트 카운터를 재설정하여 기존 알람을 지울 수 있습니다.

스토리지 노드의 구성 설정 및 카운터에 액세스하려면 다음 단계를 따르십시오.

.단계
. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다.
. 사이트 _ * > * _ 스토리지 노드 _ * 를 선택합니다.
. 스토리지 노드를 확장하고 서비스 또는 구성 요소를 선택합니다.
. Configuration * 탭을 선택합니다.


다음 표에는 스토리지 노드 구성 설정이 요약되어 있습니다.



== LDR

[cols="2a,1a,3a"]
|===
| 속성 이름 | 코드 | 설명 


 a| 
HTTP 상태
 a| 
HSTE
 a| 
S3, Swift 및 기타 내부 StorageGRID 트래픽에 대한 현재 HTTP 상태:

* 오프라인: 작업이 허용되지 않으며 LDR 서비스에 대한 HTTP 세션을 열려고 하는 모든 클라이언트 응용 프로그램에서 오류 메시지가 표시됩니다. 활성 세션이 정상적으로 닫힙니다.
* Online(온라인): 작업이 정상적으로 계속됩니다




 a| 
HTTP를 자동으로 시작합니다
 a| 
HTAS
 a| 
* 이 옵션을 선택하면 재시작 시 시스템 상태는 * LDR * > * 스토리지 * 구성 요소의 상태에 따라 달라집니다. 재시작 시 * LDR * > * 스토리지 * 구성 요소가 읽기 전용인 경우 HTTP 인터페이스도 읽기 전용입니다. LDR * > * 스토리지 * 구성 요소가 온라인인 경우 HTTP도 온라인입니다. 그렇지 않으면 HTTP 인터페이스가 오프라인 상태로 유지됩니다.
* 선택되지 않은 경우 HTTP 인터페이스는 명시적으로 활성화될 때까지 오프라인 상태로 유지됩니다.


|===


== LDR > 데이터 저장소 를 선택합니다

[cols="2a,1a,3a"]
|===
| 속성 이름 | 코드 | 설명 


 a| 
손실된 개체 수를 재설정합니다
 a| 
RCOR
 a| 
이 서비스의 손실된 개체 수에 대한 카운터를 재설정합니다.

|===


== LDR > 스토리지

[cols="2a,1a,3a"]
|===
| 속성 이름 | 코드 | 설명 


 a| 
Storage State -- 원하는 상태입니다
 a| 
SSD를 지원합니다
 a| 
스토리지 구성 요소의 원하는 상태에 대해 사용자가 구성할 수 있는 설정입니다. LDR 서비스는 이 값을 읽고 이 속성에 표시된 상태와 일치시킵니다. 이 값은 다시 시작할 때 영구적으로 유지됩니다.

예를 들어 사용 가능한 저장 공간이 충분한 경우에도 이 설정을 사용하여 저장소를 읽기 전용으로 만들 수 있습니다. 이는 문제 해결에 유용할 수 있습니다.

특성은 다음 값 중 하나를 사용할 수 있습니다.

* 오프라인: 원하는 상태가 오프라인이면 LDR 서비스에서 * LDR * > * 스토리지 * 구성 요소를 오프라인으로 전환합니다.
* 읽기 전용: 원하는 상태가 읽기 전용인 경우 LDR 서비스는 저장소 상태를 읽기 전용으로 이동하고 새 콘텐츠 수락을 중지합니다. 그러나 LDR 서비스는 S3 또는 ILM 기반 삭제 및 삭제 요청을 계속 수락합니다. 열려 있는 세션이 닫힐 때까지 콘텐츠가 잠시 동안 스토리지 노드에 계속 저장될 수 있습니다.
* Online(온라인): 일반 시스템 작업 중에 값을 Online(온라인)으로 유지합니다. 스토리지 구성 요소의 스토리지 상태 -- 현재 상태는 LDR 서비스의 상태(예: 사용 가능한 오브젝트 스토리지 공간)를 기준으로 서비스에 의해 동적으로 설정됩니다. 공간이 부족하면 구성 요소가 읽기 전용이 됩니다.




 a| 
상태 점검 시간 초과
 a| 
SHCT
 a| 
스토리지 볼륨이 양호한 것으로 간주되려면 상태 점검 테스트를 완료해야 하는 시간 제한(초)입니다. 지원 부서에서 이 값을 변경하도록 지시하는 경우에만 이 값을 변경하십시오.

|===


== LDR > 확인 을 누릅니다

[cols="2a,1a,3a"]
|===
| 속성 이름 | 코드 | 설명 


 a| 
누락된 개체 수를 재설정합니다
 a| 
VCMI
 a| 
감지된 누락된 개체 수(OMIS)를 재설정합니다. 개체 존재 확인이 완료된 후에만 사용합니다. 누락된 복제 객체 데이터는 StorageGRID 시스템에 의해 자동으로 복구됩니다.



 a| 
검증 비율
 a| 
VPRI
 a| 
백그라운드 검증이 실행되는 속도를 설정합니다. 백그라운드 검증 비율 구성에 대한 자세한 내용은 을 참조하십시오.



 a| 
손상된 개체 수를 재설정합니다
 a| 
VCCR
 a| 
백그라운드 확인 중에 발견된 손상된 복제된 개체 데이터에 대한 카운터를 재설정합니다. 이 옵션은 손상된 물체 감지(OCOR) 알람 조건을 지우는 데 사용할 수 있습니다.



 a| 
격리된 개체 삭제
 a| 
합니다
 a| 
격리 디렉터리에서 손상된 개체를 삭제하고, 격리된 개체의 수를 0으로 재설정하고, 격리된 개체 감지(OQRT) 경보를 지웁니다. 이 옵션은 손상된 개체가 StorageGRID 시스템에 의해 자동으로 복구된 후에 사용됩니다.

개체 손실 경보가 트리거되면 기술 지원 부서에서 격리된 개체에 액세스하려고 할 수 있습니다. 경우에 따라 격리된 개체는 데이터 복구나 손상된 개체 복사본을 발생시킨 기본 문제를 디버깅하는 데 유용할 수 있습니다.

|===


== LDR > 삭제 코딩

[cols="2a,1a,3a"]
|===
| 속성 이름 | 코드 | 설명 


 a| 
쓰기 실패 횟수를 재설정합니다
 a| 
RSWF
 a| 
삭제 코딩 오브젝트 데이터의 쓰기 실패에 대한 카운터를 스토리지 노드로 재설정합니다.



 a| 
재설정 읽기 실패 횟수
 a| 
SRF
 a| 
스토리지 노드에서 삭제 코딩 오브젝트 데이터의 읽기 실패에 대한 카운터를 재설정합니다.



 a| 
재설정 실패 횟수를 삭제합니다
 a| 
RSDF
 a| 
스토리지 노드에서 삭제 코딩 오브젝트 데이터의 삭제 실패에 대한 카운터를 재설정합니다.



 a| 
손상된 복제본 감지 수를 재설정합니다
 a| 
RSCC
 a| 
스토리지 노드에서 삭제 코딩 오브젝트 데이터의 손상된 복제본 수에 대한 카운터를 재설정합니다.



 a| 
손상된 조각 감지됨 카운트 재설정
 a| 
RSCCD를 참조하십시오
 a| 
스토리지 노드에서 삭제 코딩 오브젝트 데이터의 손상된 조각에 대한 카운터를 재설정합니다.



 a| 
누락된 조각 감지 횟수를 재설정합니다
 a| 
RSMD
 a| 
스토리지 노드에서 삭제 코딩 오브젝트 데이터의 누락된 조각에 대한 카운터를 재설정합니다. 개체 존재 확인이 완료된 후에만 사용합니다.

|===


== LDR > 복제

[cols="2a,1a,3a"]
|===
| 속성 이름 | 코드 | 설명 


 a| 
인바운드 복제 실패 수를 재설정합니다
 a| 
RICR
 a| 
인바운드 복제 실패에 대한 카운터를 재설정합니다. RIRF(Inbound Replication - - Failed) 경보를 지우는 데 사용할 수 있습니다.



 a| 
아웃바운드 복제 실패 수를 재설정합니다
 a| 
ROCR
 a| 
아웃바운드 복제 실패에 대한 카운터를 재설정합니다. RORF(아웃바운드 복제 - - 실패) 경보를 지우는 데 사용할 수 있습니다.



 a| 
인바운드 복제를 비활성화합니다
 a| 
DSIR
 a| 
유지 관리 또는 테스트 절차의 일부로 인바운드 복제를 사용하지 않도록 설정하려면 선택합니다. 정상 작동 중에 선택하지 않은 상태로 둡니다.

인바운드 복제를 비활성화하면 StorageGRID 시스템의 다른 위치로 복사하기 위해 스토리지 노드에서 객체를 검색할 수 있지만 LDR 서비스는 읽기 전용이라는 다른 위치에서 이 스토리지 노드에 객체를 복사할 수 없습니다.



 a| 
아웃바운드 복제를 비활성화합니다
 a| 
DSOR
 a| 
유지 관리 또는 테스트 절차의 일부로 아웃바운드 복제(HTTP 검색을 위한 콘텐츠 요청 포함)를 사용하지 않도록 설정하려면 선택합니다. 정상 작동 중에 선택하지 않은 상태로 둡니다.

아웃바운드 복제를 사용하지 않도록 설정하면 객체를 이 스토리지 노드에 복제할 수 있지만 StorageGRID 시스템의 다른 위치로 복제할 스토리지 노드에서 객체를 검색할 수는 없습니다. LDR 서비스는 쓰기 전용입니다.

|===