---
permalink: s3/complete-multipart-upload.html 
sidebar: sidebar 
keywords: multipart upload, object, object size 
summary: CompleteMultipartUpload 작업은 이전에 업로드한 부품을 조립하여 객체의 다중 부분 업로드를 완료합니다. 
---
= CompleteMultipartUpload를 클릭합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CompleteMultipartUpload 작업은 이전에 업로드한 부품을 조립하여 객체의 다중 부분 업로드를 완료합니다.



== 충돌 해결

동일한 키에 쓰는 두 클라이언트 등의 충돌하는 클라이언트 요청은 "최신 성공" 기준으로 해결됩니다. "Latest-WINS" 평가 시기는 S3 클라이언트가 작업을 시작할 때가 아니라 StorageGRID 시스템이 지정된 요청을 완료하는 시점을 기준으로 합니다.



== 요청 헤더

를 클릭합니다 `x-amz-storage-class` 요청 헤더가 지원되며 일치하는 ILM 규칙이 이중 커밋 또는 밸런스를 지정할 경우 StorageGRID에서 생성하는 객체 복제본 수에 영향을 줍니다 link:../ilm/data-protection-options-for-ingest.html["수집 옵션"].

* `STANDARD`
+
(기본값) ILM 규칙이 이중 커밋 옵션을 사용하거나 균형 옵션이 중간 복사본 생성으로 돌아올 때 이중 커밋 수집 작업을 지정합니다.

* `REDUCED_REDUNDANCY`
+
ILM 규칙이 이중 커밋 옵션을 사용하거나 균형 옵션이 중간 복사본 생성으로 돌아올 때 단일 커밋 수집 작업을 지정합니다.

+

NOTE: S3 오브젝트 잠금이 설정된 버킷으로 오브젝트를 밀어넣는 경우, 를 참조하십시오 `REDUCED_REDUNDANCY` 옵션이 무시됩니다. 오브젝트를 레거시 준수 버킷으로 인스팅하는 경우, 를 참조하십시오 `REDUCED_REDUNDANCY` 옵션을 사용하면 오류가 반환됩니다. StorageGRID은 규정 준수 요구 사항이 충족될 수 있도록 항상 이중 커밋 수집을 수행합니다.




CAUTION: 15일 이내에 여러 부분 업로드가 완료되지 않으면 작업이 비활성으로 표시되고 모든 관련 데이터가 시스템에서 삭제됩니다.


NOTE: 를 클릭합니다 `ETag` 반환된 값은 MD5 합계가 아니라 의 Amazon S3 API 구현을 따릅니다 `ETag` 다중 파트 개체에 대한 값입니다.



== 버전 관리

이 작업은 여러 부분 업로드를 완료합니다. 버켓에 대해 버전 관리가 활성화된 경우 다중 파트 업로드가 완료된 후 개체 버전이 생성됩니다.

버켓에 대해 버전 관리가 활성화된 경우 고유한 가 사용됩니다 `versionId` 는 저장 중인 개체의 버전에 대해 자동으로 생성됩니다. 여기 `versionId` 를 사용하여 응답에서도 반환됩니다 `x-amz-version-id` 응답 헤더.

버전 관리가 일시 중단된 경우 개체 버전은 null로 저장됩니다 `versionId` null 버전이 이미 있는 경우 덮어쓰기가 됩니다.


NOTE: 버켓에 대해 버전 관리가 활성화된 경우, 같은 개체 키에서 동시 다중 파트 업로드가 완료된 경우에도 다중 파트 업로드를 완료하면 항상 새 버전이 생성됩니다. 버켓에 대해 버전 관리를 사용하지 않으면 다중 파트 업로드를 시작한 다음 다른 다중 파트 업로드를 시작하여 동일한 개체 키에서 먼저 완료할 수 있습니다. 비버전 버킷에서는 마지막으로 완료한 다중 파트 업로드가 우선 적용됩니다.



== 복제, 알림 또는 메타데이터 알림에 실패했습니다

플랫폼 서비스에 대해 다중 파트 업로드가 발생하는 버킷이 구성된 경우 연결된 복제 또는 알림 작업이 실패한 경우에도 다중 파트 업로드가 성공합니다.

이 경우 SMTT(Grid Manager on Total Events)에서 경보가 발생합니다. 마지막 이벤트 메시지에는 알림이 실패한 마지막 객체에 대한 "bucket-nameobject 키에 대한 알림을 게시하지 못했습니다."라는 메시지가 표시됩니다. (이 메시지를 보려면 * nodes * > *_Storage Node_ * > * Events * 를 선택합니다. 테이블 상단의 마지막 이벤트 보기) 이벤트 메시지는 에도 나열됩니다 `/var/local/log/bycast-err.log`.

테넌트는 개체의 메타데이터 또는 태그를 업데이트하여 실패한 복제 또는 알림을 트리거할 수 있습니다. 테넌트는 불필요한 변경을 방지하기 위해 기존 값을 다시 제출할 수 있습니다.
