---
permalink: monitor/alarms-reference.html 
sidebar: sidebar 
keywords: alarms, alarms reference 
summary: 다음 표에는 레거시 기본 경보가 모두 나열되어 있습니다. 알람이 트리거되면 이 표에서 알람 코드를 조회하여 권장 조치를 찾을 수 있습니다. 
---
= 알람 기준(레거시 시스템)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 표에는 레거시 기본 경보가 모두 나열되어 있습니다. 알람이 트리거되면 이 표에서 알람 코드를 조회하여 권장 조치를 찾을 수 있습니다.


NOTE: 기존 알람 시스템은 계속 지원되지만, 알림 시스템은 상당한 이점을 제공하며 사용이 간편합니다.

[cols="1a,1a,1a,3a"]
|===
| 코드 | 이름 | 서비스 | 권장 조치 


 a| 
ABRL
 a| 
사용 가능한 특성 릴레이
 a| 
BDC, BAMS, BARC, BCLB, BCMN, BLDR, BNMS, BSSM, BDDS
 a| 
속성 릴레이 서비스를 실행하는 서비스(ADC 서비스)에 대한 연결을 가능한 한 빨리 복원합니다. 연결된 특성 릴레이가 없는 경우 그리드 노드는 NMS 서비스에 특성 값을 보고할 수 없습니다. 따라서 NMS 서비스는 더 이상 서비스의 상태를 모니터링하거나 서비스의 속성을 업데이트할 수 없습니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
ACMS
 a| 
사용 가능한 메타데이터 서비스
 a| 
BARC, BLDR, BCMN
 a| 
LDR 또는 ARC 서비스가 DDS 서비스에 대한 연결을 끊으면 경보가 발생합니다. 이 경우 수집 또는 검색 트랜잭션을 처리할 수 없습니다. DDS 서비스를 사용할 수 없게 되는 것이 일시적인 문제일 경우 트랜잭션이 지연될 수 있습니다.

DDS 서비스에 대한 연결을 확인 및 복원하여 이 경보를 지우고 서비스를 전체 기능으로 되돌립니다.



 a| 
행동합니다
 a| 
Cloud Tiering Service 상태
 a| 
호
 a| 
타겟 클라우드 계층화의 유형이 S3(Simple Storage Service)인 아카이브 노드에만 사용할 수 있습니다.

아카이브 노드의 ACTS 속성이 읽기 전용 설정 또는 읽기-쓰기 비활성 으로 설정된 경우 속성을 읽기-쓰기 사용 으로 설정해야 합니다.

인증 실패로 인해 주요 경보가 트리거되는 경우 대상 버킷과 연결된 자격 증명을 확인하고 필요한 경우 값을 업데이트합니다.

다른 이유로 인해 주요 경보가 발생하는 경우 기술 지원 부서에 문의하십시오.



 a| 
고급
 a| 
ADC 상태
 a| 
ADC
 a| 
알람이 트리거되면 * support * > * Tools * > * Grid topology * 를 선택합니다. 그런 다음 *_site_ * > *_GRID node_ * > * ADC * > * Overview * > * Main * 및 * ADC * > * Alarms * > * Main * 을 선택하여 알람 원인을 확인합니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
고급
 a| 
ADC 상태
 a| 
ADC
 a| 
ADC 상태 값이 Standby(대기) 인 경우 서비스 모니터링을 계속하고 문제가 지속되면 기술 지원 부서에 문의하십시오.

ADC 상태 값이 오프라인이면 서비스를 다시 시작합니다. 문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
아ITE
 a| 
상태 검색
 a| 
BARC
 a| 
타겟 유형이 TSM(Tivoli Storage Manager)인 아카이브 노드에만 사용할 수 있습니다.

Retrieve State 값이 Target을 기다리는 경우 TSM 미들웨어 서버를 확인하고 올바르게 작동하는지 확인합니다. 아카이브 노드가 StorageGRID 시스템에 방금 추가된 경우 대상 외부 아카이브 스토리지 시스템에 대한 아카이브 노드의 연결이 올바르게 구성되어 있는지 확인합니다.

아카이브 검색 상태 값이 오프라인인 경우 상태를 온라인으로 업데이트해 봅니다. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다. 그런 다음 *_site_ * > *_GRID node_ * > * ARC * > * Retrieve * > * Configuration * > * Main * 을 선택하고 * Archive Retrieve State * > * Online * 을 선택한 다음 * Apply Changes * 를 클릭합니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
AITU
 a| 
상태 검색
 a| 
BARC
 a| 
검색 상태 값이 대상 오류인 경우 대상 외부 아카이브 스토리지 시스템에서 오류를 확인하십시오.

Archive Retrieve Status 값이 Session Lost인 경우 대상이 지정된 외부 아카이브 스토리지 시스템이 온라인 상태이고 올바르게 작동하는지 확인합니다. 대상과의 네트워크 연결을 확인합니다.

아카이브 검색 상태 값이 알 수 없는 오류인 경우 기술 지원 부서에 문의하십시오.



 a| 
ALIS
 a| 
인바운드 속성 세션
 a| 
ADC
 a| 
속성 릴레이의 인바운드 속성 세션 수가 너무 커지면 StorageGRID 시스템이 균형을 잃어 있음을 나타낼 수 있습니다. 정상적인 조건에서 특성 세션은 ADC 서비스 간에 균등하게 분산되어야 합니다. 불균형은 성능 문제를 야기할 수 있습니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
알로스
 a| 
아웃바운드 속성 세션
 a| 
ADC
 a| 
ADC 서비스는 많은 속성 세션을 가지고 있으며 과부하가 되고 있습니다. 이 경보가 트리거되면 기술 지원 부서에 문의하십시오.



 a| 
알로
 a| 
연결할 수 없는 속성 리포지토리
 a| 
ADC
 a| 
NMS 서비스와의 네트워크 연결을 확인하여 서비스가 속성 리포지토리에 연결할 수 있는지 확인합니다.

이 경보가 트리거되고 네트워크 연결이 양호한 경우 기술 지원 부서에 문의하십시오.



 a| 
AMQS
 a| 
감사 메시지가 대기 중입니다
 a| 
BDC, BAMS, BARC, BCLB, BCMN, BLDR, BNMS, BDDS
 a| 
감사 메시지를 즉시 감사 릴레이 또는 리포지토리로 전달할 수 없는 경우 메시지는 디스크 대기열에 저장됩니다. 디스크 대기열이 가득 차면 중단이 발생할 수 있습니다.

가동 중단을 방지하기 위해 적시에 응답할 수 있도록 디스크 대기열의 메시지 수가 다음 임계값에 도달하면 AMQS 알람이 트리거됩니다.

* 주의사항: 100,000개 이상의 메시지
* Minor(최소): 최소 500,000개의 메시지
* Major: 최소 2,000,000개의 메시지
* 위험: 최소 5,000,000개의 메시지


AMQS 알람이 트리거되면 시스템의 부하를 점검합니다. 트랜잭션이 상당히 많이 발생한 경우 알람이 시간 경과에 따라 자동으로 해결되어야 합니다. 이 경우 알람을 무시할 수 있습니다.

경보가 지속되고 심각도가 증가하면 대기열 크기의 차트를 보십시오. 시간이 경과하거나 며칠 동안 꾸준히 증가하는 경우 감사 로드가 시스템의 감사 용량을 초과할 가능성이 높습니다. 감사 수준을 오류 또는 끄기로 변경하여 클라이언트 작업 속도를 줄이거나 기록된 감사 메시지 수를 줄입니다. 을 참조하십시오 link:../monitor/configure-audit-messages.html["감사 메시지 및 로그 대상을 구성합니다"].



 a| 
AOTE
 a| 
Store State(상태 저장)
 a| 
BARC
 a| 
타겟 유형이 TSM(Tivoli Storage Manager)인 아카이브 노드에만 사용할 수 있습니다.

Store State 값이 Target을 기다리는 경우, 외부 아카이브 스토리지 시스템을 확인하고 올바르게 작동하는지 확인합니다. 아카이브 노드가 StorageGRID 시스템에 방금 추가된 경우 대상 외부 아카이브 스토리지 시스템에 대한 아카이브 노드의 연결이 올바르게 구성되어 있는지 확인합니다.

Store State 값이 Offline 인 경우 Store Status 값을 확인합니다. Store State(매장 상태)를 다시 Online(온라인)으로 이동하기 전에 문제를 해결하십시오.



 a| 
AOTU
 a| 
저장 상태
 a| 
BARC
 a| 
Store Status 값이 Session Lost인 경우 외부 아카이브 스토리지 시스템이 연결되어 있고 온라인 상태인지 확인합니다.

Target Error 값이 있는 경우 외부 아카이브 스토리지 시스템에서 오류를 확인합니다.

스토어 상태 값이 알 수 없는 오류인 경우 기술 지원 부서에 문의하십시오.



 a| 
APMS
 a| 
스토리지 다중 경로 연결
 a| 
SSM
 a| 
다중 경로 상태 경보가 "Degraded"(* 지원 * > * Tools * > * Grid topology * 선택)로 표시되면 *_site_ * > * _grid node_ * > * SSM * > * Events * 선택)를 수행한 후 다음을 수행합니다.

. 표시등이 표시되지 않는 케이블을 연결하거나 교체합니다.
. 1-5분 정도 기다립니다.
+
첫 번째 케이블을 연결한 후 5분 이상 다른 케이블을 뽑지 마십시오. 너무 일찍 플러그를 뽑으면 루트 볼륨이 읽기 전용으로 되어 하드웨어를 다시 시작해야 할 수 있습니다.

. SSM * > * 리소스 * 페이지로 돌아가서 스토리지 하드웨어 섹션에서 "성능 저하" 다중 경로 상태가 "공칭"으로 변경되었는지 확인합니다.




 a| 
ARCE
 a| 
호 상태
 a| 
호
 a| 
ARC 서비스는 모든 ARC 구성 요소(복제, 저장, 검색, 대상)가 시작될 때까지 대기 상태를 가집니다. 그런 다음 온라인으로 전환됩니다.

ARC 상태 값이 Standby(대기)에서 Online(온라인)으로 전환되지 않는 경우 ARC 구성 요소의 상태를 확인합니다.

ARC State 값이 Offline 인 경우 서비스를 재시작합니다. 문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
AROQ
 a| 
개체가 대기 중입니다
 a| 
호
 a| 
이 경보는 대상 외부 아카이브 스토리지 시스템의 문제로 인해 이동식 저장 장치가 느리게 실행되거나 여러 개의 읽기 오류가 발생한 경우에 발생할 수 있습니다. 외부 아카이브 스토리지 시스템에서 오류가 있는지 확인하고 제대로 작동하는지 확인합니다.

경우에 따라 데이터 요청 비율이 높기 때문에 이 오류가 발생할 수 있습니다. 시스템 활동이 감소함에 따라 대기 중인 개체의 수를 모니터링합니다.



 a| 
ARRF
 a| 
요청 실패
 a| 
호
 a| 
대상 외부 아카이브 스토리지 시스템에서 검색에 실패하면 아카이브 노드는 일시적인 문제로 인해 장애가 발생할 수 있으므로 검색을 다시 시도합니다. 그러나 개체 데이터가 손상되었거나 영구적으로 사용할 수 없는 것으로 표시된 경우에는 검색이 실패하지 않습니다. 대신 아카이브 노드는 검색을 계속 재시도하며 요청 실패 값은 계속 증가합니다.

이 경보는 요청된 데이터를 보관하는 저장 미디어가 손상되었음을 나타낼 수 있습니다. 문제를 더 자세히 진단하려면 외부 아카이브 스토리지 시스템을 확인하십시오.

객체 데이터가 더 이상 아카이브에 없는 것으로 판단될 경우 객체를 StorageGRID 시스템에서 제거해야 합니다. 자세한 내용은 기술 지원 부서에 문의하십시오.

이 알람을 트리거한 문제가 해결되면 실패 수를 재설정합니다. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다. 그런 다음 *_site_ * > *_GRID node_ * > * ARC * > * Retrieve * > * Configuration * > * Main * 을 선택하고 * Reset Request Failure Count * 를 선택한 후 * Apply Changes * 를 클릭합니다.



 a| 
ARRV
 a| 
확인 실패
 a| 
호
 a| 
이 문제를 진단하고 해결하려면 기술 지원 부서에 문의하십시오.

이 알람을 트리거한 문제가 해결되면 실패 횟수를 재설정하십시오. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다. 그런 다음 *_site_ * > *_GRID node_ * > * ARC * > * Retrieve * > * Configuration * > * Main * 을 선택하고 * Reset Verification Failure Count * 를 선택한 후 * Apply Changes * 를 클릭합니다.



 a| 
ARVF
 a| 
저장 실패
 a| 
호
 a| 
이 경보는 대상 외부 아카이브 스토리지 시스템의 오류로 인해 발생할 수 있습니다. 외부 아카이브 스토리지 시스템에서 오류가 있는지 확인하고 제대로 작동하는지 확인합니다.

이 알람을 트리거한 문제가 해결되면 실패 수를 재설정합니다. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다. 그런 다음 *_site_ * > *_GRID node_ * > * ARC * > * Retrieve * > * Configuration * > * Main * 을 선택하고 * Reset Store Failure Count * 를 선택한 다음 * Apply Changes * 를 클릭합니다.



 a| 
ASXP
 a| 
공유 감사
 a| 
AMS
 a| 
Audit Shares의 값이 Unknown인 경우 알람이 발생합니다. 이 경보는 관리 노드의 설치 또는 구성에 문제가 있음을 나타낼 수 있습니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
8월
 a| 
AMS 상태
 a| 
AMS
 a| 
AMS Status 값이 DB Connectivity Error인 경우 GRID 노드를 다시 시작한다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
자동
 a| 
AMS 상태
 a| 
AMS
 a| 
AMS 상태 값이 Standby(대기) 인 경우 StorageGRID 시스템 모니터링을 계속합니다. 문제가 지속되면 기술 지원 팀에 문의하십시오.

AMS State 값이 Offline 인 경우, 서비스를 다시 시작한다. 문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
AUXS
 a| 
감사 내보내기 상태
 a| 
AMS
 a| 
알람이 트리거되면 기본 문제를 해결한 다음 AMS 서비스를 다시 시작합니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
BADD
 a| 
스토리지 컨트롤러 오류 드라이브 수
 a| 
SSM
 a| 
이 경보는 StorageGRID 어플라이언스에 있는 하나 이상의 드라이브가 고장났거나 최적 상태가 아닐 때 발생합니다. 필요에 따라 드라이브를 교체하십시오.



 a| 
BASF
 a| 
사용 가능한 개체 식별자
 a| 
CMN
 a| 
StorageGRID 시스템이 프로비저닝되면 CMN 서비스에 고정된 수의 오브젝트 식별자가 할당됩니다. 이 경보는 StorageGRID 시스템이 개체 식별자의 공급을 배가하기 시작할 때 트리거됩니다.

더 많은 식별자를 할당하려면 기술 지원 부서에 문의하십시오.



 a| 
중저음
 a| 
식별자 블록 할당 상태
 a| 
CMN
 a| 
기본적으로 ADC 쿼럼에 도달할 수 없기 때문에 개체 식별자를 할당할 수 없는 경우 경보가 트리거됩니다.

CMN 서비스에 대한 식별자 블록 할당을 수행하려면 ADC 서비스의 쿼럼(50% + 1)이 온라인 및 연결되어야 합니다. 쿼럼을 사용할 수 없는 경우 CMN 서비스는 ADC 쿼럼이 다시 설정될 때까지 새 식별자 블록을 할당할 수 없습니다. ADC 쿼럼이 손실된 경우 일반적으로 StorageGRID 시스템에 즉각적인 영향을 주지 않습니다(클라이언트는 콘텐츠를 수집하고 검색할 수 있음). 약 한 달 동안 ID가 그리드의 다른 위치에 캐시되기 때문입니다. 그러나 이러한 상황이 계속되면 StorageGRID 시스템이 새 콘텐츠를 수집하는 기능을 잃게 됩니다.

알람이 트리거되면 ADC quorum이 손실된 이유(예: 네트워크 또는 스토리지 노드 장애)를 조사하여 수정 조치를 취합니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
BRDT
 a| 
컴퓨팅 컨트롤러 섀시 온도
 a| 
SSM
 a| 
StorageGRID 어플라이언스의 컴퓨팅 컨트롤러 온도가 공칭 임계값을 초과할 경우 알람이 트리거됩니다.

하드웨어 구성 요소 및 환경 문제가 과열되었는지 확인합니다. 필요한 경우 구성 요소를 교체합니다.



 a| 
BTOF
 a| 
오프셋
 a| 
BDC, BLDR, BNMS, BMS, BCLB, BCMN, BARC
 a| 
서비스 시간(초)이 운영 체제 시간과 크게 다를 경우 알람이 트리거됩니다. 정상적인 상황에서는 서비스가 자체적으로 재동기화되어야 합니다. 서비스 시간이 운영 체제 시간에서 너무 멀리 떨어져 있는 경우 시스템 작동에 영향을 줄 수 있습니다. StorageGRID 시스템의 시간 소스가 올바른지 확인합니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
BTSE
 a| 
시계 상태
 a| 
BDC, BLDR, BNMS, BMS, BCLB, BCMN, BARC
 a| 
서비스 시간이 운영 체제에서 추적한 시간과 동기화되지 않으면 경보가 발생합니다. 정상적인 상황에서는 서비스가 자체적으로 재동기화되어야 합니다. 시간이 운영 체제 시간에서 너무 멀리 떨어져 있는 경우 시스템 작동에 영향을 줄 수 있습니다. StorageGRID 시스템의 시간 소스가 올바른지 확인합니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
CAHP
 a| 
Java 힙 사용량 백분율
 a| 
DDS
 a| 
Java가 시스템이 제대로 작동할 수 있도록 충분한 힙 공간을 허용하는 속도로 가비지 수집을 수행할 수 없는 경우 알람이 트리거됩니다. 이 경보는 DDS 메타데이터 저장소에 대해 시스템 전체에서 사용 가능한 리소스를 초과하는 사용자 작업 부하를 나타낼 수 있습니다. 대시보드에서 ILM 활동을 확인하거나 * 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택한 다음 *_사이트_ * > * _GRID 노드_ * > * DDS * > * 리소스 * > * 개요 * > * 주 * 를 선택합니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
카사
 a| 
데이터 저장소 상태
 a| 
DDS
 a| 
Cassandra 메타데이터 저장소를 사용할 수 없게 되면 알람이 발생합니다.

Cassandra 상태 확인:

. 스토리지 노드에서 admin 및 으로 로그인합니다 `su` Passwords.txt 파일에 나열된 암호를 사용하여 root로 설정합니다.
. 입력: `service cassandra status`
. Cassandra가 실행되고 있지 않으면 다시 시작합니다. `service cassandra restart`


이 경보는 또한 스토리지 노드의 메타데이터 저장소(Cassandra 데이터베이스)를 재구축해야 함을 나타낼 수 있습니다.

에서 서비스:상태-Cassandra(SVST) 알람 문제 해결에 대한 정보를 참조하십시오 link:../troubleshoot/troubleshooting-metadata-issues.html["메타데이터 문제를 해결합니다"].

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
케이스
 a| 
데이터 저장소 상태
 a| 
DDS
 a| 
이 경보는 설치 또는 확장 중에 새 데이터 저장소가 그리드에 가입되고 있음을 나타내기 위해 트리거됩니다.



 a| 
CCNA
 a| 
컴퓨팅 하드웨어
 a| 
SSM
 a| 
이 경보는 StorageGRID 어플라이언스의 컴퓨팅 컨트롤러 하드웨어 상태에 주의가 필요한 경우에 발생합니다.



 a| 
CDLP
 a| 
사용된 메타데이터 공간(퍼센트)
 a| 
DDS
 a| 
이 경보는 CEMS(Metadata Effective Space)가 70% 차(Minor 알람), 90% 차(Major 알람) 및 100% 차(Critical 알람)에 도달할 때 트리거됩니다.

이 경보가 90% 임계값에 도달하면 그리드 관리자의 대시보드에 경고가 나타납니다. 가능한 빨리 확장 절차를 수행하여 새 스토리지 노드를 추가해야 합니다. 을 참조하십시오 link:../expand/index.html["그리드를 확장합니다"].

이 경보가 100% 임계값에 도달하면 객체 인제스트를 중지하고 스토리지 노드를 즉시 추가해야 합니다. Cassandra에는 컴팩션 및 복원과 같은 중요 작업을 수행하려면 일정 양의 공간이 필요합니다. 오브젝트 메타데이터에서 허용되는 공간의 100% 이상을 사용하는 경우 이러한 작업이 영향을 받습니다. 원치 않는 결과가 발생할 수 있습니다.

* 참고 *: 스토리지 노드를 추가할 수 없는 경우 기술 지원 부서에 문의하십시오.

새 스토리지 노드가 추가되면 시스템이 모든 스토리지 노드에서 개체 메타데이터를 자동으로 재조정하며 경보가 지워집니다.

에서 메타데이터 부족 스토리지 알림 문제 해결에 대한 정보도 참조하십시오 link:../troubleshoot/troubleshooting-metadata-issues.html["메타데이터 문제를 해결합니다"].

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
CMNA
 a| 
CMN 상태
 a| 
CMN
 a| 
CMN 상태 값이 오류인 경우 * 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택한 다음 *_사이트 _ * > * _GRID NODE_ * > * CMN * > * 개요 * > * 메인 * 및 * CMN * > * 알람 * > * 메인 * 을 선택하여 오류의 원인을 확인하고 문제를 해결하십시오.

CMN이 전환될 때 기본 관리 노드의 하드웨어 새로 고침 중에 알람이 트리거되고 CMN 상태 값이 온라인 CMN이 아닙니다(이전 CMN 상태 값은 대기 상태이고 새 값은 온라인).

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
CPRC
 a| 
남은 용량
 a| 
NMS
 a| 
남은 용량(NMS 데이터베이스에서 열 수 있는 사용 가능한 연결 수)이 구성된 알람 심각도 미만으로 떨어지면 알람이 트리거됩니다.

알람이 트리거되면 기술 지원 팀에 문의하십시오.



 a| 
CPSA
 a| 
컴퓨팅 컨트롤러 전원 공급 장치 A
 a| 
SSM
 a| 
StorageGRID 어플라이언스의 컴퓨팅 컨트롤러에 전원 공급 장치 A에 문제가 있는 경우 알람이 트리거됩니다.

필요한 경우 구성 요소를 교체합니다.



 a| 
cPSB
 a| 
컴퓨팅 컨트롤러 전원 공급 장치 B
 a| 
SSM
 a| 
StorageGRID 어플라이언스의 컴퓨팅 컨트롤러에 전원 공급 장치 B에 문제가 있는 경우 알람이 트리거됩니다.

필요한 경우 구성 요소를 교체합니다.



 a| 
CPUT
 a| 
컴퓨팅 컨트롤러 CPU 온도
 a| 
SSM
 a| 
StorageGRID 어플라이언스의 컴퓨팅 컨트롤러에 있는 CPU 온도가 공칭 임계값을 초과하면 경보가 발생합니다.

스토리지 노드가 StorageGRID 어플라이언스인 경우 StorageGRID 시스템에서 컨트롤러에 주의가 필요함을 나타냅니다.

하드웨어 구성 요소 및 환경 문제가 과열되었는지 확인합니다. 필요한 경우 구성 요소를 교체합니다.



 a| 
NST
 a| 
DNS 상태
 a| 
SSM
 a| 
설치가 완료되면 SSM 서비스에서 NST 알람이 트리거됩니다. DNS를 구성하고 새 서버 정보가 모든 그리드 노드에 도달하면 알람이 취소됩니다.



 a| 
ECCD
 a| 
손상된 조각이 감지되었습니다
 a| 
LDR
 a| 
백그라운드 확인 프로세스에서 손상된 삭제 코딩 조각을 감지하면 경보가 발생합니다. 손상된 조각이 발견되면 조각을 재생성하려고 시도합니다. 손상된 조각을 재설정하고 손실된 속성을 0으로 복사하며, 이를 모니터링하여 카운트 다시 증가 여부를 확인합니다. 카운트가 상향 이동되면 스토리지 노드의 기본 스토리지에 문제가 있을 수 있습니다. 삭제로 코딩된 오브젝트 데이터의 복사본은 손실되거나 손상된 조각의 수가 삭제 코드의 내결함성을 위반하기 전까지는 누락된 것으로 간주되지 않습니다. 따라서 조각이 손상되어 오브젝트를 계속 검색할 수 있습니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
ECST
 a| 
확인 상태
 a| 
LDR
 a| 
이 경보는 이 스토리지 노드에서 삭제 코딩된 객체 데이터에 대한 백그라운드 검증 프로세스의 현재 상태를 나타냅니다.

백그라운드 검증 프로세스에 오류가 있는 경우 주요 경보가 트리거됩니다.



 a| 
부품 번호
 a| 
파일 설명자를 엽니다
 a| 
BDC, BAMS, BARC, BCLB, BCMN, BLDR, BNMS, BSSM, BDDS
 a| 
FOPN은 최대 활동 중에 크기가 커질 수 있습니다. 활동이 느린 기간 동안 감소하지 않으면 기술 지원 부서에 문의하십시오.



 a| 
HSTE
 a| 
HTTP 상태
 a| 
흑백
 a| 
HSTU에 대한 권장 조치를 참조하십시오.



 a| 
HSTU
 a| 
HTTP 상태
 a| 
흑백
 a| 
HSTE 및 HSTU는 S3, Swift 및 기타 내부 StorageGRID 트래픽을 비롯한 모든 LDR 트래픽에 대해 HTTP와 연결됩니다. 경보는 다음 상황 중 하나가 발생했음을 나타냅니다.

* HTTP가 수동으로 오프라인 상태로 전환되었습니다.
* 자동 시작 HTTP 특성이 비활성화되었습니다.
* LDR 서비스가 종료되는 중입니다.


자동 시작 HTTP 속성은 기본적으로 활성화되어 있습니다. 이 설정을 변경하면 다시 시작한 후에 HTTP가 오프라인 상태로 유지될 수 있습니다.

필요한 경우 LDR 서비스가 다시 시작될 때까지 기다립니다.

지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다. 그런 다음 *_스토리지 노드_ * > * LDR * > * 구성 * 을 선택합니다. HTTP가 오프라인이면 온라인으로 전환합니다. HTTP 자동 시작 속성이 활성화되어 있는지 확인합니다.

HTTP가 오프라인 상태로 유지되는 경우 기술 지원 부서에 문의하십시오.



 a| 
HTAS
 a| 
HTTP를 자동으로 시작합니다
 a| 
LDR
 a| 
시작 시 HTTP 서비스를 자동으로 시작할지 여부를 지정합니다. 사용자 지정 구성 옵션입니다.



 a| 
IRSU
 a| 
인바운드 복제 상태
 a| 
BLDR, BARC
 a| 
인바운드 복제가 비활성화되었음을 알리는 경보가 표시됩니다. 구성 설정 확인: * 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다. 그런 다음 *_site_ * > *_GRID node_ * > * LDR * > * Replication * > * Configuration * > * Main * 을 선택합니다.



 a| 
라타
 a| 
평균 지연 시간
 a| 
NMS
 a| 
연결 문제를 확인합니다.

시스템 활동을 점검하여 시스템 활동이 증가하는지 확인하십시오. 시스템 활동이 증가하면 특성 데이터 활동이 증가합니다. 이렇게 활동이 증가하면 특성 데이터 처리가 지연됩니다. 이는 정상적인 시스템 활동일 수 있으며 하위 작업이 될 수 있습니다.

여러 개의 알람을 점검합니다. 평균 지연 시간 증가는 트리거된 알람의 과다한 수로 나타날 수 있습니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
LDRE
 a| 
LDR 상태
 a| 
LDR
 a| 
LDR 상태 값이 대기 인 경우, 상태를 계속 모니터링하고 문제가 지속되면 기술 지원 부서에 문의하십시오.

LDR 상태 값이 오프라인인 경우 서비스를 다시 시작합니다. 문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
분실
 a| 
손실된 개체
 a| 
DDS, LDR
 a| 
StorageGRID 시스템이 시스템 내의 모든 위치에서 요청된 개체의 복사본을 검색하지 못할 때 트리거됩니다. 손실(개체 손실) 경보가 트리거되기 전에 시스템은 시스템의 다른 위치에서 누락된 개체를 검색하고 교체하려고 시도합니다.

손실된 개체는 데이터 손실을 나타냅니다. 손실된 개체 속성은 DDS 서비스가 ILM 정책을 충족하기 위해 의도적으로 컨텐츠를 퍼지하지 않고 객체의 위치 수가 0으로 떨어질 때마다 증가합니다.

분실(객체 손실) 알람을 즉시 조사하십시오. 문제가 지속되면 기술 지원 팀에 문의하십시오.

link:../troubleshoot/troubleshooting-lost-and-missing-object-data.html["분실하거나 누락된 오브젝트 데이터 문제를 해결합니다"]



 a| 
MCEP
 a| 
관리 인터페이스 인증서 만료
 a| 
CMN
 a| 
관리 인터페이스에 액세스하는 데 사용되는 인증서가 곧 만료될 때 트리거됩니다.

. 그리드 관리자에서 * 구성 * > * 보안 * > * 인증서 * 를 선택합니다.
. 글로벌 * 탭에서 * 관리 인터페이스 인증서 * 를 선택합니다.
. link:../admin/configuring-custom-server-certificate-for-grid-manager-tenant-manager.html#add-a-custom-management-interface-certificate["새 관리 인터페이스 인증서를 업로드합니다."]




 a| 
마인큐
 a| 
이메일 알림 대기 중
 a| 
NMS
 a| 
NMS 서비스를 호스팅하는 서버 및 외부 메일 서버의 네트워크 연결을 확인합니다. 또한 이메일 서버 구성이 올바른지 확인하십시오.

link:managing-alarms.html["경보에 대한 이메일 서버 설정 구성(레거시 시스템)"]



 a| 
분
 a| 
이메일 알림 상태
 a| 
BNMS
 a| 
NMS 서비스가 메일 서버에 연결할 수 없는 경우 보조 경보가 발생합니다. NMS 서비스를 호스팅하는 서버 및 외부 메일 서버의 네트워크 연결을 확인합니다. 또한 이메일 서버 구성이 올바른지 확인하십시오.

link:managing-alarms.html["경보에 대한 이메일 서버 설정 구성(레거시 시스템)"]



 a| 
놓칠 수 있습니다
 a| 
NMS 인터페이스 엔진 상태
 a| 
BNMS
 a| 
관리 노드의 NMS 인터페이스 엔진이 시스템에서 인터페이스 컨텐츠를 수집하고 생성하는 경우 알람이 트리거됩니다. 서버 관리자 를 선택하여 서버 개별 응용 프로그램이 다운되었는지 확인합니다.



 a| 
Nang
 a| 
네트워크 자동 협상 설정
 a| 
SSM
 a| 
네트워크 어댑터 구성을 확인합니다. 이 설정은 네트워크 라우터 및 스위치의 기본 설정과 일치해야 합니다.

잘못된 설정은 시스템 성능에 심각한 영향을 줄 수 있습니다.



 a| 
NDUP
 a| 
네트워크 이중 모드 설정
 a| 
SSM
 a| 
네트워크 어댑터 구성을 확인합니다. 이 설정은 네트워크 라우터 및 스위치의 기본 설정과 일치해야 합니다.

잘못된 설정은 시스템 성능에 심각한 영향을 줄 수 있습니다.



 a| 
NLNK
 a| 
네트워크 링크 감지
 a| 
SSM
 a| 
포트와 스위치에서 네트워크 케이블 연결을 확인합니다.

네트워크 라우터, 스위치 및 어댑터 구성을 확인합니다.

서버를 다시 시작합니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
NRER
 a| 
수신 오류
 a| 
SSM
 a| 
NRER 알람의 원인은 다음과 같습니다.

* 정방향 오류 수정(FEC)이 일치하지 않습니다
* 스위치 포트와 NIC MTU가 일치하지 않습니다
* 높은 링크 오류율
* NIC 링 버퍼 오버런


에서 NRER(Network Receive Error) 경보 문제 해결에 대한 정보를 참조하십시오 link:../troubleshoot/troubleshooting-network-hardware-and-platform-issues.html["네트워크, 하드웨어 및 플랫폼 문제를 해결합니다"].



 a| 
NRLY
 a| 
사용 가능한 감사 릴레이
 a| 
BDC, BARC, BCLB, BCMN, BLDR, BNMS, BDDS
 a| 
감사 릴레이가 ADC 서비스에 연결되어 있지 않으면 감사 이벤트를 보고할 수 없습니다. 연결이 복원될 때까지 사용자가 대기하며 사용할 수 없습니다.

ADC 서비스에 대한 연결을 가능한 한 빨리 복원합니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
NSCA
 a| 
NMS 상태
 a| 
NMS
 a| 
NMS Status 값이 DB Connectivity Error인 경우 서비스를 다시 시작합니다. 문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
NSCE
 a| 
NMS 상태
 a| 
NMS
 a| 
NMS 상태 값이 Standby(대기) 인 경우 모니터링을 계속하고 문제가 지속되면 기술 지원 부서에 문의하십시오.

NMS State 값이 Offline 인 경우, 서비스를 다시 시작한다. 문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
NSPD
 a| 
속도
 a| 
SSM
 a| 
이 문제는 네트워크 연결 또는 드라이버 호환성 문제로 인해 발생할 수 있습니다. 문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
NTBR
 a| 
사용 가능한 테이블스페이스
 a| 
NMS
 a| 
알람이 트리거되면 데이터베이스 사용량이 얼마나 빠르게 변경되었는지 확인합니다. 시간이 지남에 따라 점진적으로 변경되는 것이 아니라 갑작스런 드롭은 오류 상태를 나타냅니다. 문제가 지속되면 기술 지원 팀에 문의하십시오.

알람 임계값을 조정하면 추가 스토리지를 할당해야 할 때 사전 예방적으로 관리할 수 있습니다.

사용 가능한 공간이 하한 임계값에 도달하면(알람 임계값 참조) 기술 지원 부서에 문의하여 데이터베이스 할당을 변경합니다.



 a| 
네터
 a| 
전송 오류
 a| 
SSM
 a| 
이러한 오류는 수동으로 다시 설정하지 않고 지울 수 있습니다. 확실하지 않은 경우 네트워크 하드웨어를 확인하십시오. 어댑터 하드웨어 및 드라이버가 네트워크 라우터 및 스위치와 작동하도록 올바르게 설치 및 구성되었는지 확인합니다.

기본 문제가 해결되면 카운터를 재설정합니다. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다. 그런 다음 *_site_ * > *_GRID node_ * > * SSM * > * Resources * > * Configuration * > * Main * 을 선택하고 * Reset Transmit Error Count * 를 선택한 다음 * Apply Changes * 를 클릭합니다.



 a| 
NTFQ
 a| 
NTP 주파수 오프셋
 a| 
SSM
 a| 
주파수 오프셋이 구성된 임계값을 초과하는 경우 로컬 클럭에 하드웨어 문제가 있을 수 있습니다. 문제가 지속되면 기술 지원 팀에 문의하여 교체를 요청하십시오.



 a| 
NTLK
 a| 
NTP 잠금
 a| 
SSM
 a| 
NTP 데몬이 외부 시간 소스에 잠기지 않은 경우 지정된 외부 시간 소스, 해당 가용성 및 안정성에 대한 네트워크 연결을 확인합니다.



 a| 
NTOF
 a| 
NTP 시간 오프셋
 a| 
SSM
 a| 
시간 오프셋이 구성된 임계값을 초과하는 경우 로컬 시계의 발진기에 하드웨어 문제가 있을 수 있습니다. 문제가 지속되면 기술 지원 팀에 문의하여 교체를 요청하십시오.



 a| 
NTSJ
 a| 
선택한 시간 소스 지터
 a| 
SSM
 a| 
이 값은 로컬 서버의 NTP가 참조로 사용하는 시간 소스의 안정성 및 안정성을 나타냅니다.

알람이 트리거되면 시간 소스의 발진기에 결함이 있거나 시간 소스에 대한 WAN 링크에 문제가 있음을 나타낼 수 있습니다.



 a| 
NTSU
 a| 
NTP 상태입니다
 a| 
SSM
 a| 
NTP 상태 값이 실행되고 있지 않으면 기술 지원 부서에 문의하십시오.



 a| 
OPST
 a| 
전체 전원 상태
 a| 
SSM
 a| 
StorageGRID 제품의 전원이 권장 작동 전압과 차이가 나는 경우 알람이 트리거됩니다.

전원 공급 장치 A 또는 B의 상태를 점검하여 어떤 전원 공급 장치가 비정상적으로 작동하는지 확인합니다.

필요한 경우 전원 공급 장치를 교체합니다.



 a| 
합니다
 a| 
개체를 격리했습니다
 a| 
LDR
 a| 
StorageGRID 시스템에서 개체를 자동으로 복원한 후에는 격리된 개체를 격리 디렉터리에서 제거할 수 있습니다.

. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다.
. site * > * Storage Node * > * LDR * > * Verification * > * Configuration * > * Main * 을 선택합니다.
. 격리된 개체 삭제 * 를 선택합니다.
. 변경 내용 적용 * 을 클릭합니다.


격리된 객체가 제거되고 개수가 0으로 재설정됩니다.



 a| 
ORSU
 a| 
아웃바운드 복제 상태입니다
 a| 
BLDR, BARC
 a| 
알람은 아웃바운드 복제가 가능하지 않음을 나타냅니다. 스토리지가 객체를 검색할 수 없는 상태입니다. 아웃바운드 복제를 수동으로 비활성화하면 경보가 트리거됩니다. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다. 그런 다음 *_site_ * > *_GRID node_ * > * LDR * > * Replication * > * Configuration * 을 선택합니다.

LDR 서비스를 복제할 수 없는 경우 알람이 트리거됩니다. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다. 그런 다음 *_site_ * > *_GRID node_ * > * LDR * > * Storage * 를 선택합니다.



 a| 
OSLF
 a| 
쉘프 상태
 a| 
SSM
 a| 
스토리지 어플라이언스의 스토리지 쉘프에 있는 구성 요소 중 하나의 상태가 저하되면 알람이 트리거됩니다. 스토리지 쉘프 구성 요소에는 IOM, 팬, 전원 공급 장치 및 드라이브 드로어가 포함됩니다. 이 경보가 발생하면 어플라이언스에 대한 유지 관리 지침을 참조하십시오.



 a| 
PMEM
 a| 
서비스 메모리 사용량(%)
 a| 
BDC, BAMS, BARC, BCLB, BCMN, BLDR, BNMS, BSSM, BDDS
 a| 
Y% RAM 이상의 값을 가질 수 있습니다. 여기서 Y는 서버에서 사용 중인 메모리의 백분율을 나타냅니다.

80% 미만의 수치는 정상입니다. 90% 이상이 문제로 간주됩니다.

단일 서비스에 대한 메모리 사용량이 높은 경우 상황을 모니터링하고 조사합니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
PSA
 a| 
전원 공급 장치 A 상태
 a| 
SSM
 a| 
StorageGRID 제품의 전원 공급 장치 A가 권장 작동 전압과 차이가 나는 경우 알람이 트리거됩니다.

필요한 경우 전원 공급 장치 A를 교체합니다



 a| 
PSBS
 a| 
전원 공급 장치 B 상태
 a| 
SSM
 a| 
StorageGRID 제품의 전원 공급 장치 B가 권장 작동 전압과 차이가 나는 경우 알람이 트리거됩니다.

필요한 경우 전원 공급 장치 B를 교체합니다



 a| 
RDTE
 a| 
Tivoli Storage Manager 상태입니다
 a| 
BARC
 a| 
타겟 유형이 TSM(Tivoli Storage Manager)인 아카이브 노드에만 사용할 수 있습니다.

Tivoli Storage Manager State의 값이 Offline인 경우 Tivoli Storage Manager Status를 확인하여 문제를 해결하십시오.

구성 요소를 다시 온라인 상태로 전환합니다. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다. 그런 다음 *_site_ * > *_GRID node_ * > * ARC * > * Target * > * Configuration * > * Main * 을 선택하고 * Tivoli Storage Manager State * > * Online * 을 선택한 다음 * Apply Changes * 를 클릭합니다.



 a| 
RDTU
 a| 
Tivoli Storage Manager 상태입니다
 a| 
BARC
 a| 
타겟 유형이 TSM(Tivoli Storage Manager)인 아카이브 노드에만 사용할 수 있습니다.

Tivoli Storage Manager Status의 값이 Configuration Error 이고 아카이브 노드가 StorageGRID 시스템에 방금 추가된 경우 TSM 미들웨어 서버가 올바르게 구성되어 있는지 확인하십시오.

Tivoli Storage Manager Status의 값이 Connection Failure 또는 Connection Failure인 경우, 재시도 시 TSM 미들웨어 서버의 네트워크 구성과 TSM 미들웨어 서버와 StorageGRID 시스템 간의 네트워크 연결을 확인하십시오.

Tivoli Storage Manager Status의 값이 Authentication Failure 또는 Authentication Failure인 경우 Reconnecting인 경우 StorageGRID 시스템은 TSM 미들웨어 서버에 연결할 수 있지만 연결을 인증할 수 없습니다. TSM 미들웨어 서버가 올바른 사용자, 암호 및 권한으로 구성되어 있는지 확인하고 서비스를 다시 시작합니다.

Tivoli Storage Manager Status의 값이 Session Failure인 경우, 설정된 세션이 예기치 않게 손실되었습니다. TSM 미들웨어 서버와 StorageGRID 시스템 간의 네트워크 연결을 확인합니다. 미들웨어 서버에 오류가 있는지 확인합니다.

Tivoli Storage Manager Status의 값이 Unknown Error인 경우 기술 지원 부서에 문의하십시오.



 a| 
RIRF
 a| 
인바운드 복제 -- 실패
 a| 
BLDR, BARC
 a| 
인바운드 복제 -- 장애가 발생한 알람은 로드가 높거나 일시적인 네트워크 중단 기간 동안 발생할 수 있습니다. 시스템 활동이 감소하면 이 경보가 해제됩니다. 실패한 복제 수가 계속 증가하는 경우 네트워크 문제를 찾아 소스 및 대상 LDR 및 ARC 서비스가 온라인 상태이고 사용 가능한지 확인합니다.

개수를 재설정하려면 * 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택한 다음 *_사이트_ * > * _GRID 노드_ * > * LDR * > * 복제 * > * 구성 * > * 주 * 를 선택합니다. Reset Inbound Replication Failure Count * 를 선택하고 * Apply Changes * 를 클릭합니다.



 a| 
RIRQ
 a| 
인바운드 복제 -- 대기 중
 a| 
BLDR, BARC
 a| 
알람은 부하가 높거나 일시적인 네트워크 중단 기간 동안 발생할 수 있습니다. 시스템 활동이 감소하면 이 경보가 해제됩니다. 대기 중인 복제 수가 계속 증가하는 경우 네트워크 문제를 찾아 소스 및 대상 LDR 및 ARC 서비스가 온라인 상태이고 사용 가능한지 확인합니다.



 a| 
RORQ
 a| 
아웃바운드 복제 -- 대기열에 있습니다
 a| 
BLDR, BARC
 a| 
아웃바운드 복제 큐에는 ILM 규칙 및 클라이언트가 요청한 객체를 충족하기 위해 복제되는 객체 데이터가 포함되어 있습니다.

시스템 과부하로 인해 알람이 발생할 수 있다. 시스템 활동이 감소하면 경보가 해제되는지 확인할 때까지 기다립니다. 알람이 다시 발생하면 스토리지 노드를 추가하여 용량을 추가합니다.



 a| 
SAVP
 a| 
총 사용 가능한 공간(%)
 a| 
LDR
 a| 
사용 가능한 공간이 낮은 임계값에 도달하면 StorageGRID 시스템을 확장하거나 아카이브 노드를 통해 아카이브할 객체 데이터를 이동하는 옵션이 포함됩니다.



 a| 
CA
 a| 
상태
 a| 
CMN
 a| 
활성 그리드 작업의 상태 값이 오류인 경우 그리드 작업 메시지를 찾습니다. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다. 그런 다음 *_site_ * > *_GRID node_ * > * CMN * > * Grid Tasks * > * Overview * > * Main * 을 선택합니다. 그리드 작업 메시지에는 오류에 대한 정보가 표시됩니다(예: "노드 12130011에서 검사 실패").

문제를 조사하고 해결한 후 그리드 작업을 다시 시작합니다. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다. 그런 다음 *_site_ * > *_GRID node_ * > * CMN * > * Grid Tasks * > * Configuration * > * Main * 을 선택하고 * Actions * > * Run * 을 선택합니다.

중지되는 그리드 작업의 상태 값이 오류인 경우 그리드 작업을 다시 종료해 보십시오.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
SCEP
 a| 
스토리지 API 서비스 엔드포인트 인증서 만료
 a| 
CMN
 a| 
스토리지 API 엔드포인트를 액세스하는 데 사용되는 인증서가 곧 만료될 때 트리거됩니다.

. 구성 * > * 보안 * > * 인증서 * 를 선택합니다.
. 글로벌 * 탭에서 * S3 및 Swift API 인증서 * 를 선택합니다.
. link:../admin/configuring-custom-server-certificate-for-storage-node.html#add-a-custom-s3-and-swift-api-certificate["새 S3 및 Swift API 인증서를 업로드합니다."]




 a| 
SCHR
 a| 
상태
 a| 
CMN
 a| 
내역 그리드 작업의 상태 값이 중단된 경우 이유를 조사하고 필요한 경우 작업을 다시 실행합니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
SCSA
 a| 
스토리지 컨트롤러 A
 a| 
SSM
 a| 
StorageGRID 어플라이언스에서 스토리지 컨트롤러 A에 문제가 있는 경우 알람이 트리거됩니다.

필요한 경우 구성 요소를 교체합니다.



 a| 
SCSB
 a| 
스토리지 컨트롤러 B
 a| 
SSM
 a| 
StorageGRID 어플라이언스에서 스토리지 컨트롤러 B에 문제가 있는 경우 알람이 트리거됩니다.

필요한 경우 구성 요소를 교체합니다.

일부 어플라이언스 모델에는 스토리지 컨트롤러 B가 없습니다



 a| 
SHLH
 a| 
상태
 a| 
LDR
 a| 
오브젝트 저장소의 상태 값이 오류인 경우 다음을 확인하고 수정하십시오.

* 마운트하는 볼륨에 문제가 있습니다
* 파일 시스템 오류입니다




 a| 
SLSA
 a| 
CPU 로드 평균
 a| 
SSM
 a| 
값이 클수록 시스템이 더 많이 사용됩니다.

CPU Load Average(CPU 로드 평균)가 높은 값으로 지속될 경우 시스템의 트랜잭션 수를 조사하여 해당 시점에 로드가 과부하인지 여부를 확인해야 합니다. CPU 로드 평균의 차트를 봅니다. * 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다. 그런 다음 *_site_ * > *_GRID node_ * > * SSM * > * Resources * > * Reports * > * Charts * 를 선택합니다.

시스템의 로드가 무겁지 않고 문제가 지속되면 기술 지원 부서에 문의하십시오.



 a| 
SMST
 a| 
로그 모니터 상태
 a| 
SSM
 a| 
로그 모니터 상태 값이 지속적으로 연결되지 않은 경우 기술 지원 부서에 문의하십시오.



 a| 
SMTT
 a| 
총 이벤트
 a| 
SSM
 a| 
Total Events 값이 0보다 큰 경우, 원인이 될 수 있는 알려진 이벤트(예: 네트워크 장애)가 있는지 확인합니다. 이러한 오류가 지워지지 않은 경우(즉, 카운트가 0으로 재설정됨) 전체 이벤트 알람이 트리거될 수 있습니다.

문제가 해결되면 카운터를 재설정하여 경보를 지웁니다. nodes * > *_site_ * > *_GRID node_ * > * Events * > * Reset event counts * 를 선택합니다.


NOTE: 이벤트 수를 재설정하려면 그리드 토폴로지 페이지 구성 권한이 있어야 합니다.

총 이벤트 수가 0이거나 숫자가 증가하고 문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
SNST
 a| 
상태
 a| 
CMN
 a| 
알람은 그리드 작업 번들을 저장하는 데 문제가 있음을 나타냅니다. Status 값이 Checkpoint Error 또는 Quorum Not reached인 경우, ADC 서비스 대부분이 StorageGRID 시스템에 연결되어 있는지 확인한 다음(50% + 1) 몇 분 정도 기다립니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
SOSS
 a| 
스토리지 운영 체제 상태입니다
 a| 
SSM
 a| 
SANtricity OS에서 StorageGRID 어플라이언스의 구성 요소에 "주의 필요" 문제가 있다고 표시할 경우 경보가 발생합니다.

노드 * 를 선택합니다. 그런 다음 * 어플라이언스 스토리지 노드 * > * 하드웨어 * 를 선택합니다. 각 구성 요소의 상태를 보려면 아래로 스크롤합니다. SANtricity OS에서 다른 어플라이언스 구성 요소를 확인하여 문제를 파악합니다.



 a| 
SSMA
 a| 
SSM 상태
 a| 
SSM
 a| 
SSM Status 값이 Error인 경우 * support * > * Tools * > * Grid topology * 를 선택한 후 *_site_ * > * _GRID node_ * > * SSM * > * Overview * > * Main * 및 * SSM * > * Overview * > * Alarms * 를 선택하여 알람 원인을 파악합니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
SSME
 a| 
SSM 상태
 a| 
SSM
 a| 
SSM 상태 값이 Standby(대기) 인 경우 모니터링을 계속하고 문제가 지속되면 기술 지원 부서에 문의하십시오.

SSM State 값이 Offline 인 경우 서비스를 다시 시작한다. 문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
SSTS
 a| 
저장소 상태
 a| 
흑백
 a| 
스토리지 상태 값이 가용 공간이 부족하면 스토리지 노드에 사용 가능한 스토리지가 더 이상 없으며 데이터 베스트 데이터가 사용 가능한 다른 스토리지 노드로 리디렉션됩니다. 검색 요청은 이 그리드 노드에서 계속 전달될 수 있습니다.

추가 스토리지를 추가해야 합니다. 최종 사용자 기능에는 영향을 미치지 않지만 추가 스토리지가 추가될 때까지 경보가 지속됩니다.

저장소 상태 값이 볼륨을 사용할 수 없는 경우 저장소 일부를 사용할 수 없습니다. 이러한 볼륨에서의 저장 및 검색은 불가능합니다. 자세한 내용은 볼륨 상태를 확인하십시오. * 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택하십시오. 그런 다음 *_site_ * > *_GRID node_ * > * LDR * > * Storage * > * Overview * > * Main * 을 선택합니다. 볼륨의 상태는 오브젝트 저장소 아래에 나열됩니다.

스토리지 상태 값이 오류 인 경우 기술 지원 부서에 문의하십시오.

link:../troubleshoot/troubleshooting-storage-status-alarm.html["SSTS(Storage Status) 경보 문제를 해결합니다"]



 a| 
SVST
 a| 
상태
 a| 
SSM
 a| 
이 알람은 실행되지 않는 서비스와 관련된 다른 알람이 해결되면 해제됩니다. 소스 서비스 경보를 추적하여 작업을 복구합니다.

지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다. 그런 다음 *_site_ * > *_GRID node_ * > * SSM * > * Services * > * Overview * > * Main * 을 선택합니다. 서비스 상태가 Not Running 으로 표시되면 서비스 상태가 Administratively Down 으로 표시됩니다. 서비스 상태는 다음과 같은 이유로 Not Running(실행되지 않음) 으로 표시될 수 있습니다.

* 서비스가 수동으로 중지되었습니다 (`/etc/init.d/<service\> stop`)를 클릭합니다.
* MySQL 데이터베이스에 문제가 있으며 Server Manager가 MI 서비스를 종료합니다.
* 그리드 노드가 추가되었지만 시작되지 않았습니다.
* 설치 중에 그리드 노드가 아직 관리 노드에 연결되지 않았습니다.


서비스가 실행 중이 아닌 것으로 표시되면 서비스를 다시 시작합니다 (`/etc/init.d/<service\> restart`)를 클릭합니다.

이 경보는 또한 스토리지 노드의 메타데이터 저장소(Cassandra 데이터베이스)를 재구축해야 함을 나타낼 수 있습니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.

link:../troubleshoot/troubleshooting-metadata-issues.html["서비스: 상태 - Cassandra(SVST) 알람 문제를 해결합니다"]



 a| 
TMEM
 a| 
메모리를 설치했습니다
 a| 
SSM
 a| 
설치된 메모리 용량이 24GiB 미만인 노드를 실행하면 성능 문제와 시스템 불안정으로 이어질 수 있습니다. 시스템에 설치된 메모리 양을 24GiB 이상으로 늘려야 합니다.



 a| 
TPOP
 a| 
보류 중인 작업
 a| 
ADC
 a| 
메시지 큐는 ADC 서비스가 과부하되었음을 나타낼 수 있습니다. StorageGRID 시스템에 연결할 수 있는 ADC 서비스가 너무 적습니다. 대규모 배포에서는 ADC 서비스에 컴퓨팅 리소스를 추가해야 하거나 시스템에 추가 ADC 서비스가 필요할 수 있습니다.



 a| 
메모리
 a| 
사용 가능한 메모리
 a| 
SSM
 a| 
사용 가능한 RAM이 부족한 경우 이것이 하드웨어 문제인지 소프트웨어 문제인지 확인합니다. 하드웨어 문제가 아니거나 사용 가능한 메모리가 50MB(기본 알람 임계값) 미만인 경우 기술 지원 부서에 문의하십시오.



 a| 
VMFI
 a| 
사용 가능한 항목
 a| 
SSM
 a| 
이는 추가 보관이 필요함을 나타냅니다. 기술 지원 부서에 문의하십시오.



 a| 
VMFR
 a| 
사용 가능한 공간
 a| 
SSM
 a| 
사용 가능한 공간 값이 너무 낮으면(알람 임계값 참조), 로그 파일의 비율이 초과되었는지 또는 디스크 공간이 너무 많은 개체(알람 임계값 참조)를 축소 또는 삭제해야 하는지 여부를 조사해야 합니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.



 a| 
VMST
 a| 
상태
 a| 
SSM
 a| 
마운트된 볼륨의 상태 값이 알 수 없는 경우 알람이 트리거됩니다. Unknown 또는 Offline 값은 기본 스토리지 디바이스의 문제로 인해 볼륨을 마운트하거나 액세스할 수 없음을 나타낼 수 있습니다.



 a| 
VPRI
 a| 
검증 우선 순위
 a| 
BLDR, BARC
 a| 
기본적으로 검증 우선 순위 값은 적응 입니다. Verification Priority(확인 우선 순위)가 High(높음)로 설정된 경우, 스토리지 확인 시 서비스의 정상적인 작동이 느려질 수 있기 때문에 알람이 트리거됩니다.



 a| 
VSTU
 a| 
개체 검증 상태
 a| 
흑백
 a| 
지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다. 그런 다음 *_site_ * > *_GRID node_ * > * LDR * > * Storage * > * Overview * > * Main * 을 선택합니다.

운영 체제에서 블록 장치 또는 파일 시스템 오류의 징후를 확인합니다.

개체 검증 상태 값이 알 수 없는 오류인 경우 일반적으로 저장소 확인 작업이 저장된 콘텐츠에 액세스하지 못하게 하는 낮은 수준의 파일 시스템 또는 하드웨어 문제(I/O 오류)를 나타냅니다. 기술 지원 부서에 문의하십시오.



 a| 
XMS
 a| 
연결할 수 없는 감사 저장소
 a| 
BDC, BARC, BCLB, BCMN, BLDR, BNMS
 a| 
관리 노드를 호스팅하는 서버에 대한 네트워크 연결을 확인합니다.

문제가 지속되면 기술 지원 팀에 문의하십시오.

|===