---
permalink: monitor/managing-alerts-and-alarms.html 
sidebar: sidebar 
keywords: how to manage alerts, what are alerts, what are alarms 
summary: StorageGRID 경고 시스템은 주의가 필요한 운영 문제를 알려주도록 설계되었습니다. 기존 경보 시스템은 더 이상 사용되지 않습니다. 
---
= 경보 및 경보 관리: 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 경고 시스템은 주의가 필요한 운영 문제를 알려주도록 설계되었습니다. 기존 경보 시스템은 더 이상 사용되지 않습니다.



== 경고 시스템

경고 시스템은 StorageGRID 시스템에서 발생할 수 있는 문제를 모니터링하는 기본 도구로 설계되었습니다. 경고 시스템은 문제 감지, 평가 및 해결을 위한 사용이 간편한 인터페이스를 제공합니다.

알림은 알림 규칙 조건이 true로 평가될 때 특정 심각도 수준에서 트리거됩니다. 경고가 트리거되면 다음 작업이 수행됩니다.

* 그리드 관리자의 대시보드에 경고 심각도 아이콘이 표시되고 현재 경고의 수가 증가합니다.
* 이 알림은 * nodes * 요약 페이지와 * nodes * > *_node_ * > * Overview * 탭에 표시됩니다.
* SMTP 서버를 구성하고 수신자에 대한 이메일 주소를 제공한 경우 이메일 알림이 전송됩니다.
* StorageGRID SNMP 에이전트를 구성한 경우 SNMP(Simple Network Management Protocol) 알림이 전송됩니다.




== 레거시 알람 시스템

경고와 마찬가지로, 속성은 정의된 임계값에 도달할 때 특정 심각도 수준에서 트리거됩니다. 그러나 알림과 달리, 많은 알람은 사용자가 안전하게 무시할 수 있는 이벤트에 대해 트리거되며, 이로 인해 e-메일 또는 SNMP 알림이 과도하게 많아질 수 있습니다.


NOTE: 알람 시스템은 더 이상 사용되지 않으며 향후 릴리즈에서 제거될 예정입니다. 기존 경보를 계속 사용하는 경우 가능한 한 빨리 경보 시스템으로 완전히 전환해야 합니다.

알람이 트리거되면 다음과 같은 동작이 발생합니다.

* 알람이 * support * > * Alarms (Legacy) * > * Current alarms * 페이지에 나타납니다.
* SMTP 서버를 구성하고 하나 이상의 메일 그룹을 구성한 경우 이메일 알림이 전송됩니다.
* StorageGRID SNMP 에이전트를 구성한 경우 SNMP 알림이 전송될 수 있습니다. (모든 알람 또는 알람 심각도에 대해 SNMP 알림이 전송되지 않습니다.)

