---
permalink: maintain/troubleshooting-node-decommissioning.html 
sidebar: sidebar 
keywords: storagegrid, recover, decommission, troubleshoot 
summary: 오류로 인해 노드 서비스 해제 절차가 중지되는 경우 특정 단계를 수행하여 문제를 해결할 수 있습니다. 
---
= 노드 사용 중단 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
오류로 인해 노드 서비스 해제 절차가 중지되는 경우 특정 단계를 수행하여 문제를 해결할 수 있습니다.

.시작하기 전에
를 사용하여 그리드 관리자에 로그인했습니다 link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"].

.이 작업에 대해
사용 중단 중인 그리드 노드를 종료하면 그리드 노드가 다시 시작될 때까지 작업이 중지됩니다. 그리드 노드는 온라인이어야 합니다.

.단계
. 지원 * > * 도구 * > * 그리드 토폴로지 * 를 선택합니다.
. 그리드 토폴로지 트리에서 각 스토리지 노드 항목을 확장하고 DDS 및 LDR 서비스가 모두 온라인 상태인지 확인합니다.
+
스토리지 노드 폐기를 수행하려면 온라인 노드/사이트 서비스 해제 시작 시 모든 노드와 서비스가 정상 상태가 되어야 합니다.

. 활성 그리드 작업을 보려면 * 기본 관리자 노드 * > * CMN * > * 그리드 작업 * > * 개요 * 를 선택합니다.
. 서비스 해제 그리드 작업의 상태를 확인합니다.
+
.. 서비스 해제 그리드 작업 상태가 그리드 작업 번들을 저장하는 데 문제가 있는 경우 * 기본 관리자 노드 * > * CMN * > * 이벤트 * > * 개요 * 를 선택합니다.
.. 사용 가능한 감사 릴레이 수를 확인합니다.
+
사용 가능한 감사 릴레이 속성이 하나 이상인 경우 CMN 서비스는 하나 이상의 ADC 서비스에 연결됩니다. ADC 서비스는 감사 릴레이 역할을 합니다.

+
CMN 서비스는 하나 이상의 ADC 서비스에 연결되어 있어야 하며 그리드 작업이 폐기 단계 간에 이동하고 완료될 수 있도록 StorageGRID 시스템의 ADC 서비스 중 과반수(50% + 1)를 사용할 수 있어야 합니다.

.. CMN 서비스가 충분한 ADC 서비스에 연결되어 있지 않으면 스토리지 노드가 온라인 상태인지 확인하고 기본 관리 노드와 스토리지 노드 간의 네트워크 연결을 확인합니다.



