---
permalink: primer/what-storage-node-is.html 
sidebar: sidebar 
keywords: what is a storage node, how many storage nodes 
summary: '스토리지 노드: 오브젝트 데이터 및 메타데이터를 관리하고 저장합니다. 스토리지 노드에는 디스크의 오브젝트 데이터와 메타데이터를 저장, 이동, 확인 및 검색하는 데 필요한 서비스와 프로세스가 포함됩니다.' 
---
= 스토리지 노드란?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드: 오브젝트 데이터 및 메타데이터를 관리하고 저장합니다. 스토리지 노드에는 디스크의 오브젝트 데이터와 메타데이터를 저장, 이동, 확인 및 검색하는 데 필요한 서비스와 프로세스가 포함됩니다.

StorageGRID 시스템의 각 사이트에는 3개 이상의 스토리지 노드가 있어야 합니다.



== 스토리지 노드 유형

StorageGRID 11.8 이전에 설치된 모든 스토리지 노드에는 오브젝트에 대한 오브젝트와 메타데이터가 모두 저장됩니다. StorageGRID 11.8부터 새 소프트웨어 기반 스토리지 노드에 대해 스토리지 노드 유형을 선택할 수 있습니다.

오브젝트 및 메타데이터 스토리지 노드:: 기본적으로 StorageGRID 11.8에 설치된 모든 신규 스토리지 노드에는 오브젝트와 메타데이터가 모두 저장됩니다.
메타데이터 전용 스토리지 노드(소프트웨어 기반 노드만):: 메타데이터만 저장하는 데 새 소프트웨어 기반 스토리지 노드를 사용하도록 지정할 수 있습니다. 또한 StorageGRID 시스템을 확장하는 동안 메타데이터 전용 소프트웨어 기반 스토리지 노드를 StorageGRID 시스템에 추가할 수 있습니다.
+
--

NOTE: 스토리지 노드 유형은 소프트웨어 기반 노드를 처음 설치할 때나 StorageGRID 시스템 확장 중에 소프트웨어 기반 노드를 설치할 때만 선택할 수 있습니다. 노드 설치가 완료된 후에는 유형을 변경할 수 없습니다.

--


일반적으로 메타데이터 전용 노드를 설치할 필요는 없습니다. 하지만 그리드에 많은 수의 작은 오브젝트가 저장되는 경우에는 메타데이터에만 스토리지 노드를 사용하는 것이 적절할 수 있습니다. 전용 메타데이터 용량을 설치하면 많은 수의 작은 개체에 필요한 공간과 모든 개체에 대한 메타데이터에 필요한 공간 사이의 균형이 향상됩니다.

소프트웨어 기반 메타데이터 전용 노드로 그리드를 설치할 경우 그리드에는 오브젝트 스토리지를 위한 최소 노드 수도 있어야 합니다.

* 단일 사이트 그리드의 경우 객체 및 메타데이터에 대해 2개 이상의 스토리지 노드가 구성됩니다.
* 다중 사이트 그리드의 경우 사이트당 하나 이상의 스토리지 노드가 객체 및 메타데이터에 대해 구성됩니다.


소프트웨어 기반 스토리지 노드는 스토리지 노드 유형을 나열하는 모든 페이지에서 각 메타데이터 전용 노드에 대한 메타데이터 전용 표시를 표시합니다.



== 스토리지 노드의 기본 서비스

다음 표에는 스토리지 노드의 기본 서비스가 나와 있지만 이 표에는 모든 노드 서비스가 나와 있지 않습니다.


NOTE: ADC 서비스 및 RSM 서비스와 같은 일부 서비스는 일반적으로 각 사이트의 세 스토리지 노드에만 존재합니다.

[cols="1a,3a"]
|===
| 서비스 | 키 기능 


 a| 
계정(acct)
 a| 
테넌트 계정을 관리합니다.



 a| 
관리 도메인 컨트롤러(ADC)
 a| 
토폴로지 및 그리드 전체의 구성 유지

.세부 정보
[%collapsible]
====
ADC(관리 도메인 컨트롤러) 서비스는 그리드 노드와 상호 연결을 인증합니다. ADC 서비스는 한 사이트에서 최소 3개의 스토리지 노드에 호스팅됩니다.

ADC 서비스는 서비스의 위치 및 가용성을 포함한 토폴로지 정보를 유지합니다. 그리드 노드에 다른 그리드 노드의 정보가 필요하거나 다른 그리드 노드에서 작업을 수행해야 하는 경우 ADC 서비스에 문의하여 요청을 처리할 최적의 그리드 노드를 찾습니다. 또한 ADC 서비스는 StorageGRID 배포의 구성 번들의 사본을 보유하므로 모든 그리드 노드가 현재 구성 정보를 검색할 수 있습니다.

분산 및 분산 작업을 용이하게 하기 위해 각 ADC 서비스는 인증서, 구성 번들 및 서비스 및 토폴로지에 대한 정보를 StorageGRID 시스템의 다른 ADC 서비스와 동기화합니다.

일반적으로 모든 그리드 노드는 하나 이상의 ADC 서비스에 대한 연결을 유지합니다. 이렇게 하면 그리드 노드가 항상 최신 정보에 액세스할 수 있습니다. 그리드 노드가 연결되면 다른 그리드 노드의 인증서를 캐시하여 ADC 서비스를 사용할 수 없는 경우에도 시스템이 알려진 그리드 노드에서 계속 작동할 수 있도록 합니다. 새 그리드 노드는 ADC 서비스를 통해서만 연결을 설정할 수 있습니다.

ADC 서비스는 각 그리드 노드의 연결을 통해 토폴로지 정보를 수집할 수 있습니다. 이 그리드 노드 정보에는 CPU 로드, 사용 가능한 디스크 공간(스토리지가 있는 경우), 지원되는 서비스 및 그리드 노드의 사이트 ID가 포함됩니다. 다른 서비스에서는 ADC 서비스에 토폴로지 쿼리를 통한 토폴로지 정보를 요청합니다. ADC 서비스는 StorageGRID 시스템에서 수신한 최신 정보로 각 쿼리에 응답합니다.

====


 a| 
Cassandra 를 클릭합니다
 a| 
오브젝트 메타데이터를 저장하고 보호합니다.



 a| 
Cassandra Refaper(Cassandra 성형기)
 a| 
오브젝트 메타데이터를 자동으로 복구합니다.



 a| 
청크
 a| 
삭제 코딩 데이터 및 패리티 조각을 관리합니다.



 a| 
Data Mover(DMV)
 a| 
데이터를 클라우드 스토리지 풀로 이동합니다.



 a| 
DDS(분산 데이터 저장소)
 a| 
오브젝트 메타데이터 스토리지를 모니터링합니다.

.세부 정보
[%collapsible]
====
각 스토리지 노드에는 DDS(Distributed Data Store) 서비스가 포함됩니다. 이 서비스는 Cassandra 데이터베이스와 연동되어 StorageGRID 시스템에 저장된 오브젝트 메타데이터에 대한 백그라운드 작업을 수행합니다.

DDS 서비스는 StorageGRID 시스템으로 수집된 총 객체 수와 시스템의 지원되는 인터페이스(S3 또는 Swift)를 통해 수집된 총 객체 수를 추적합니다.

====


 a| 
ID(idnt)
 a| 
LDAP 및 Active Directory에서 사용자 ID를 페더레이션합니다.



 a| 
LDR(Local Distribution Router)
 a| 
오브젝트 스토리지 프로토콜 요청을 처리하고 디스크의 오브젝트 데이터를 관리합니다.

.세부 정보
[%collapsible]
====
각 스토리지 노드에는 LDR(Local Distribution Router) 서비스가 포함됩니다. 이 서비스는 데이터 저장, 라우팅 및 요청 처리를 비롯한 콘텐츠 전송 기능을 처리합니다. LDR 서비스는 데이터 전송 로드 및 데이터 트래픽 기능을 처리하여 StorageGRID 시스템의 대부분의 작업을 수행합니다.

LDR 서비스는 다음 작업을 처리합니다.

* 쿼리
* ILM(정보 수명 주기 관리) 작업
* 개체 삭제
* 오브젝트 데이터 스토리지
* 다른 LDR 서비스(스토리지 노드)에서 오브젝트 데이터 전송
* 데이터 스토리지 관리
* 프로토콜 인터페이스(S3 및 Swift)


LDR 서비스는 또한 각 S3 및 Swift 개체를 고유한 UUID에 매핑합니다.

오브젝트 저장소:: LDR 서비스의 기본 데이터 스토리지는 고정된 수의 오브젝트 저장소(스토리지 볼륨이라고도 함)로 나뉩니다. 각 오브젝트 저장소는 별도의 마운트 지점입니다.
+
--
스토리지 노드의 오브젝트 저장소는 002F의 16진수 번호로 식별되며 볼륨 ID라고도 합니다. Cassandra 데이터베이스의 오브젝트 메타데이터에 대한 첫 번째 오브젝트 저장소(볼륨 0)에 공간이 예약되며, 해당 볼륨의 나머지 공간은 오브젝트 데이터에 사용됩니다. 다른 모든 오브젝트 저장소는 복제된 복사본 및 삭제 코딩 조각이 포함된 오브젝트 데이터에만 사용됩니다.

복제된 복사본에 대한 공간 사용이 고르게 되도록 지정된 개체의 개체 데이터는 사용 가능한 스토리지 공간을 기반으로 한 하나의 개체 저장소에 저장됩니다. 개체 저장소의 용량이 가득 차면 나머지 개체 저장소는 스토리지 노드에 더 이상의 공간이 없을 때까지 계속 개체를 저장합니다.

--
메타데이터 보호:: StorageGRID는 LDR 서비스와 상호 작용하는 Cassandra 데이터베이스에 개체 메타데이터를 저장합니다.
+
--
이중화를 보장하고 손실을 방지하기 위해 각 사이트에 오브젝트 메타데이터의 복사본 3개가 유지됩니다. 이 복제는 구성이 불가능하며 자동으로 수행됩니다. 자세한 내용은 을 참조하십시오 link:../admin/managing-object-metadata-storage.html["오브젝트 메타데이터 스토리지 관리"].

--


====


 a| 
복제된 상태 시스템(RSM)
 a| 
S3 플랫폼 서비스 요청이 해당 엔드포인트로 전송되도록 합니다.



 a| 
서버 상태 모니터(SSM)
 a| 
운영 체제 및 기본 하드웨어를 모니터링합니다.

|===