---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure 
summary: 스토리지 노드를 추가한 후 EC 재조정 절차를 사용하여 기존 스토리지 노드와 새 스토리지 노드 간에 삭제 코딩 조각을 재배포할 수 있습니다.  
---
= 스토리지 노드를 추가한 후 삭제 코딩 데이터의 균형을 재조정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드를 추가한 후 EC 재조정 절차를 사용하여 기존 스토리지 노드와 새 스토리지 노드 간에 삭제 코딩 조각을 재배포할 수 있습니다.

.시작하기 전에
* 새 스토리지 노드를 추가하는 확장 단계를 완료했습니다.
* 을(를) 검토했습니다 link:considerations-for-rebalancing-erasure-coded-data.html["삭제 코딩 데이터의 재조정에 대한 고려사항"].
* 복제된 오브젝트 데이터는 이 절차에 의해 이동되지 않으며 EC 재조정 절차에서는 삭제 코딩 데이터를 이동할 위치를 결정할 때 각 스토리지 노드에서 복제된 데이터 사용을 고려하지 않는다는 점을 이해합니다.
* 을(를) 보유하고 있습니다 `Passwords.txt` 파일.


.이 절차를 실행하면 어떻게 됩니까
절차를 시작하기 전에 다음 사항에 유의하십시오.

* 하나 이상의 볼륨이 오프라인 상태(마운트 해제)이거나 온라인 상태(마운트)이지만 오류 상태인 경우 EC 균형 조정 절차가 시작되지 않습니다.
* EC 재조정 절차는 많은 양의 스토리지를 임시로 예약합니다. 스토리지 알림이 트리거될 수 있지만 재조정이 완료되면 문제가 해결됩니다. 예약 저장 공간이 충분하지 않으면 EC 재조정 절차가 실패합니다. EC 재조정 절차가 완료되면 절차가 실패했는지 여부에 관계없이 스토리지 예약이 해제됩니다.
* EC 재조정 절차가 진행되는 동안 볼륨이 오프라인 상태가 되면 재조정 절차가 종료됩니다. 이미 이동된 데이터 조각은 새 위치에 유지되며 데이터는 손실되지 않습니다.
+
모든 볼륨이 다시 온라인 상태가 된 후 절차를 다시 실행할 수 있습니다.

* EC 재조정 절차가 실행 중인 경우 ILM 작업 및 S3 및 Swift 클라이언트 작업의 성능에 영향을 미칠 수 있습니다.
+

NOTE: 오브젝트(또는 오브젝트 부분)를 업로드하는 S3 및 Swift API 작업이 완료되는 데 24시간이 넘는 시간이 필요한 EC 재조정 절차 중에 실패할 수 있습니다. 해당 ILM 규칙이 수집 시 균형 또는 엄격 배치를 사용하는 경우 장기 PUT 작업이 실패합니다. 다음 오류가 보고됩니다. `500 Internal Server Error`.

* 이 절차 중에 모든 노드의 스토리지 용량은 80%로 제한됩니다. 이 제한을 초과하지만 여전히 대상 데이터 파티션 아래에 저장되는 노드는 다음 대상에서 제외됩니다.
+
** 사이트 불균형 값입니다
** 모든 작업 완료 조건
+

NOTE: 대상 데이터 파티션은 사이트의 전체 데이터를 노드 수로 나누어 계산합니다.



* * 작업 완료 조건 *. 를 클릭합니다 link:considerations-for-rebalancing-erasure-coded-data.html#what-is-ec-rebalancing.html["EC 재조정 절차"] 다음 중 하나에 해당할 경우 완료된 것으로 간주됩니다.
+
** 삭제 코딩 데이터를 더 이상 이동할 수 없습니다.
** 모든 노드의 데이터가 대상 데이터 파티션의 5% 편차 내에 있습니다.
** 이 절차는 30일 동안 실행되었습니다.




.단계
. [[review_object_storage]] 재조정할 사이트의 현재 오브젝트 스토리지 세부 정보를 검토합니다.
+
.. 노드 * 를 선택합니다.
.. 사이트에서 첫 번째 스토리지 노드를 선택합니다.
.. Storage * 탭을 선택합니다.
.. 커서를 Storage Used-Object Data 차트 위에 놓으면 스토리지 노드에서 복제된 데이터의 현재 양과 삭제 코딩 데이터를 볼 수 있습니다.
.. 사이트에서 다른 스토리지 노드를 보려면 다음 단계를 반복합니다.


. 기본 관리자 노드에 로그인합니다.
+
.. 다음 명령을 입력합니다. `ssh admin@_primary_Admin_Node_IP_`
.. 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.
.. 루트로 전환하려면 다음 명령을 입력합니다. `su -`
.. 에 나열된 암호를 입력합니다 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 에서 변경됩니다 `$` 를 선택합니다 `#`.



. 절차를 시작합니다.
+
're balance-data start--site "_site-name_"

+
"_site-name_"의 경우 새 스토리지 노드를 추가한 첫 번째 사이트를 지정합니다. 영역 추출 `site-name` 따옴표로 묶습니다.

+
EC 재조정 절차가 시작되고 작업 ID가 반환됩니다.

. 작업 ID를 복사합니다.
. [[VIEW-STATUS]] EC 재조정 절차의 상태를 모니터링합니다.
+
** 단일 EC 재조정 절차의 상태를 보려면
+
`rebalance-data status --job-id _job-id_`

+
용 `_job-id_`에서 절차를 시작할 때 반환된 ID를 지정합니다.

** 현재 EC 재조정 절차 및 이전에 완료된 절차의 상태를 보려면
+
`rebalance-data status`

+
[NOTE]
====
rebalance-data 명령에 대한 도움말을 보려면 다음을 수행합니다.

`rebalance-data --help`

====


. 반환된 상태에 따라 추가 단계를 수행합니다.
+
** If(경우 `State` 있습니다 `In progress`EC 재조정 작업이 여전히 실행 중입니다. 절차가 완료될 때까지 주기적으로 모니터링해야 합니다.
+
를 사용합니다 `Site Imbalance` 사이트의 스토리지 노드 전체에서 불균형한 삭제 코드 데이터 사용량이 어떻게 되는지 평가하기 위한 가치. 이 값의 범위는 1.0에서 0까지이며, 0은 삭제 코딩 데이터 사용량이 사이트의 모든 스토리지 노드에 걸쳐 완전히 균형 조정되었음을 나타냅니다.

+
EC 재조정 작업은 완료된 것으로 간주되며 모든 노드의 데이터가 대상 데이터 파티션의 5% 편차 내에 있을 때 중지됩니다.

** If(경우 `State` 있습니다 `Success`(선택 사항 <<review_object_storage,오브젝트 스토리지 검토>> 사이트에 대한 업데이트된 세부 정보를 봅니다.
+
이제 삭제 코딩 데이터가 사이트의 스토리지 노드 간에 더 균형 있게 균형 있게 조정되어야 합니다.

** If(경우 `State` 있습니다 `Failure`:
+
... 사이트의 모든 스토리지 노드가 그리드에 연결되어 있는지 확인합니다.
... 이러한 스토리지 노드에 영향을 줄 수 있는 알림을 확인하고 해결합니다.
... EC 재조정 절차를 다시 시작합니다.
+
`rebalance-data start –-job-id _job-id_`

... <<view-status,상태를 봅니다>> 를 참조하십시오. If(경우 `State` 이(가) 여전히 있습니다 `Failure`, 기술 지원 부서에 문의하십시오.




. EC 균형 조정 절차에서 너무 많은 로드가 생성되는 경우(예: 수집 작업이 영향을 받음) 절차를 일시 중지하십시오.
+
`rebalance-data pause --job-id _job-id_`

. EC 재조정 절차를 종료해야 하는 경우(예: StorageGRID 소프트웨어 업그레이드 수행) 다음을 입력합니다.
+
`rebalance-data terminate --job-id _job-id_`

+

NOTE: EC 재조정 절차를 종료하면 이미 이동된 데이터 조각이 새 위치에 남아 있습니다. 데이터가 원래 위치로 다시 이동되지 않습니다.

. 둘 이상의 사이트에서 삭제 코딩을 사용하는 경우 영향을 받는 다른 모든 사이트에 대해 이 절차를 실행합니다.

