---
permalink: ilm/guidelines-for-creating-storage-pools.html 
sidebar: sidebar 
keywords: storage pool guidelines 
summary: 여러 사이트에 데이터를 분산하여 데이터 손실을 방지하기 위해 스토리지 풀을 구성 및 사용합니다. 복제된 복사본 및 삭제 코딩 복사본을 사용하려면 다른 스토리지 풀 구성이 필요합니다. 
---
= 스토리지 풀 생성 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
여러 사이트에 데이터를 분산하여 데이터 손실을 방지하기 위해 스토리지 풀을 구성 및 사용합니다. 복제된 복사본 및 삭제 코딩 복사본을 사용하려면 다른 스토리지 풀 구성이 필요합니다.

을 참조하십시오 link:using-multiple-storage-pools-for-cross-site-replication.html["복제 및 삭제 코딩을 사용하여 사이트 손실을 방지할 수 있는 방법의 예"].



== 모든 스토리지 풀에 대한 지침입니다

* 스토리지 풀 구성을 가능한 한 단순하게 유지합니다. 필요한 것보다 더 많은 스토리지 풀을 생성하지 마십시오.
* 가능한 한 많은 노드를 포함하는 스토리지 풀을 생성합니다. 각 스토리지 풀에는 둘 이상의 노드가 포함되어야 합니다. 노드가 부족한 스토리지 풀은 노드를 사용할 수 없게 될 경우 ILM 백로그를 유발할 수 있습니다.
* 중복되는 스토리지 풀을 생성하거나 사용하지 마십시오(동일한 노드 중 하나 이상 포함). 스토리지 풀이 중복될 경우 오브젝트 데이터의 복제본이 동일한 노드에 저장될 수 있습니다.
* 일반적으로 모든 스토리지 노드 스토리지 풀(StorageGRID 11.6 이하) 또는 모든 사이트 사이트를 사용하지 마십시오. 이러한 항목은 확장에 추가한 새 사이트를 포함하도록 자동으로 업데이트되며, 이는 원하는 동작이 아닐 수 있습니다.




== 복제된 복제본에 사용되는 스토리지 풀에 대한 지침입니다

* 을 사용하여 사이트 손실 방지 link:what-replication-is.html["복제"]에서 하나 이상의 사이트별 스토리지 풀을 지정합니다 link:create-ilm-rule-define-placements.html["각 ILM 규칙에 대한 배치 지침"].
+
StorageGRID를 설치하는 동안 각 사이트에 대해 스토리지 풀 하나가 자동으로 생성됩니다.

+
각 사이트에 스토리지 풀을 사용하면 복제된 개체 복사본이 원하는 위치에 정확하게 배치됩니다. 예를 들어, 사이트 손실 방지를 위해 각 사이트에 있는 모든 개체의 복사본이 하나씩 배치됩니다.

* 확장 시 사이트를 추가하는 경우 새 사이트만 포함하는 새 스토리지 풀을 생성합니다. 그런 다음 link:working-with-ilm-rules-and-ilm-policies.html#edit-an-ilm-rule["ILM 규칙을 업데이트합니다"] 새 사이트에 저장되는 개체를 제어합니다.
* 복제본 수가 스토리지 풀 수보다 적은 경우 시스템은 복제본을 분산하여 풀 간에 디스크 사용량을 밸런싱합니다.
* 스토리지 풀이 겹칠 경우(동일한 스토리지 노드 포함) 개체의 모든 복제본이 하나의 사이트에만 저장될 수 있습니다. 선택한 스토리지 풀에 동일한 스토리지 노드가 포함되어 있지 않은지 확인해야 합니다.




== 삭제 코딩 복사본에 사용되는 스토리지 풀에 대한 지침입니다

* 을 사용하여 사이트 손실 방지 link:what-erasure-coding-is.html["삭제 코딩"]에서 3개 이상의 사이트로 구성된 스토리지 풀을 생성합니다. 스토리지 풀에 사이트가 두 개만 포함된 경우 해당 스토리지 풀을 삭제 코딩에 사용할 수 없습니다. 두 개의 사이트가 있는 스토리지 풀에는 삭제 코딩 스키마를 사용할 수 없습니다.
* 스토리지 풀에 포함된 스토리지 노드 및 사이트 수에 따라 결정됩니다 link:what-erasure-coding-schemes-are.html["삭제 코딩 구성표"] 를 사용할 수 있습니다.
* 가능한 경우 스토리지 풀에 선택한 삭제 코딩 체계에 필요한 최소 스토리지 노드 수보다 많은 수가 포함되어야 합니다. 예를 들어, 6+3 삭제 코딩 체계를 사용하는 경우 9개 이상의 스토리지 노드가 있어야 합니다. 그러나 사이트당 스토리지 노드를 하나 이상 추가하는 것이 좋습니다.
* 가능한 한 사이트 간에 스토리지 노드를 균등하게 분산합니다. 예를 들어, 6+3 삭제 코딩 체계를 지원하려면 세 개 사이트에 세 개 이상의 스토리지 노드를 포함하는 스토리지 풀을 구성합니다.
* 처리량이 많은 경우 여러 사이트가 포함된 스토리지 풀을 사용하는 것은 사이트 간 네트워크 지연 시간이 100ms를 초과하는 경우에는 권장되지 않습니다. 지연 시간이 늘어날수록 StorageGRID에서 TCP 네트워크 처리량이 감소하기 때문에 개체 조각을 생성, 배치 및 검색할 수 있는 속도가 급격하게 줄어듭니다.
+
처리량 감소는 오브젝트 수집 및 검색 시 달성 가능한 최대 속도에 영향을 미치거나(수집 동작으로 Balanced 또는 Strict를 선택한 경우) ILM 대기열 백로그로 이어질 수 있습니다(수집 동작으로 이중 커밋을 선택한 경우). 을 참조하십시오 link:what-ilm-rule-is.html#ilm-rule-ingest-behavior["ILM 규칙 수집 동작"].

+

NOTE: 그리드에 사이트가 하나만 포함된 경우에는 삭제 코딩 프로필에서 모든 스토리지 노드 스토리지 풀(StorageGRID 11.6 이하) 또는 모든 사이트 기본 사이트를 사용할 수 없습니다. 이 동작은 두 번째 사이트가 추가될 때 프로필이 무효화될 수 없도록 합니다.

* 삭제 코딩 데이터에는 아카이브 노드를 사용할 수 없습니다.




== 아카이빙된 복제본에 사용되는 스토리지 풀에 대한 지침입니다

[CAUTION]
====
아카이브 노드에 대한 지원은 더 이상 사용되지 않으며 향후 릴리즈에서 제거될 예정입니다. S3 API를 통해 아카이브 노드에서 외부 아카이브 스토리지 시스템으로 오브젝트를 이동한 후 ILM 클라우드 스토리지 풀로 대체되었으며 더 많은 기능을 제공합니다.

Cloud Tiering - S3(Simple Storage Service) 옵션도 더 이상 사용되지 않습니다. 현재 이 옵션으로 아카이브 노드를 사용 중인 경우 link:../admin/migrating-objects-from-cloud-tiering-s3-to-cloud-storage-pool.html["오브젝트를 클라우드 스토리지 풀로 마이그레이션합니다"] 대신

또한 StorageGRID 11.7 이하의 활성 ILM 정책에서 아카이브 노드를 제거해야 합니다. 아카이브 노드에 저장된 오브젝트 데이터를 제거하면 향후 업그레이드가 간소화됩니다. 을 참조하십시오 link:working-with-ilm-rules-and-ilm-policies.html["ILM 규칙 및 ILM 정책 작업"].

====
* 스토리지 노드와 아카이브 노드를 모두 포함하는 스토리지 풀을 생성할 수 없습니다. 아카이빙된 복제본에는 아카이브 노드만 포함된 스토리지 풀이 필요합니다.
* 아카이브 노드가 포함된 스토리지 풀을 사용하는 경우 스토리지 노드가 포함된 스토리지 풀에서 하나 이상의 복제된 복사본 또는 삭제 코딩 복사본도 유지 관리해야 합니다.
* 글로벌 S3 오브젝트 잠금 설정이 활성화되어 있고 호환되는 ILM 규칙을 생성하는 경우 아카이브 노드가 포함된 스토리지 풀을 사용할 수 없습니다. S3 오브젝트 잠금을 사용하여 오브젝트를 관리하는 지침을 참조하십시오.
* 아카이브 노드의 타겟 유형이 Cloud Tiering - Simple Storage Service(S3)인 경우 아카이브 노드는 자체 스토리지 풀에 있어야 합니다.

